### PR TITLE
Add a few more filter words

### PR DESCRIPTION
**Pull request by flexagoon**
# Related Issue/Addition to code

- Improve the filter list

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- Add "on my cha", "robux", "robucks", "sweet" and "pussy"
- Change "girls" to "girl".

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Please add even vbuck and vbucks if its not already added. Thanks

**Comment by flexagoon** [comment]
@KendallDoesCoding vbucks is already there

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding vbucks is already there

Ok cool, Approved this PR.

**Comment by EthanHindmarsh** [comment]
> Add "on my cha", "robux", "robucks", "sweet" and "pussy"

what are these bots saying 😨

LGTM

**Comment by ThioJoe** [comment]
Only one I am holding off on is "sweet", because I think it's just a bit too general

**Comment by flexagoon** [comment]
@ThioJoe I just saw some channels with the name like "sweet girls". But I guess this will be triggered by "girl" anyway

**Pull request merged**
