### PR TITLE
install.sh for dependencies 

### PR DESCRIPTION
**Pull request by lolpro11**
# Related Issue/Addition to code
- https://github.com/ThioJoe/YouTube-Spammer-Purge/issues/216

- Fixes #
- Linux setup does not work on other distros, such as Fedora 
- Other distros do not have Apt

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Additional Info
- Tkinter is a dependency (pip does not install this as a python dependency, it is a .so (shared object) binary), which this script installs.
- Please add [Linux-Installation-Instructions.md](https://github.com/lolpro11/YouTube-Spammer-Purge/blob/main/Linux-Installation-Instructions.md) as the wiki page for Linux Installation Instructions

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
> # Related Issue/Addition to code
> Please delete options that are not relevant.
> 
> * Fixes #
> * Linux setup does not work on other distros, such as Fedora
> * Other distros do not have Apt
> 
> ## Type of change
> Please delete options that are not relevant.
> 
> * [x]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [x]  This change requires a documentation update
> 
> # Additional Info
> * Tkinter is a dependency (pip does not install this as a python dependency, it is a .so (shared object) binary), which this script installs.
> * Please add [Linux-Installation-Instructions.md](https://github.com/lolpro11/YouTube-Spammer-Purge/blob/main/Linux-Installation-Instructions.md) as the wiki page for Linux Installation Instructions
> 
> ## Checklist:
> * [x]  My code follows the style guidelines of this project and have read CONTRIBUTING.md
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented on my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [ ]  My changes generate no new warnings
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  New and existing unit tests pass locally with my changes
> * [ ]  Any dependent changes have been merged and published in downstream modules
> * [x]  I have checked my code and corrected any misspellings

Can you please make a issue thread for this and within Fixes # mention that issue number? Thanks

**Comment by KendallDoesCoding** [comment]
> > # Related Issue/Addition to code
> > Please delete options that are not relevant.
> > 
> > * Fixes #
> > * Linux setup does not work on other distros, such as Fedora
> > * Other distros do not have Apt
> > 
> > ## Type of change
> > Please delete options that are not relevant.
> > 
> > * [x]   Bug fix (non-breaking change which fixes an issue)
> > * [x]   New feature (non-breaking change which adds functionality)
> > * [x]   Breaking change (fix or feature that would cause existing functionality to not work as expected)
> > * [x]   This change requires a documentation update
> > 
> > # Additional Info
> > 
> > * Tkinter is a dependency (pip does not install this as a python dependency, it is a .so (shared object) binary), which this script installs.
> > * Please add [Linux-Installation-Instructions.md](https://github.com/lolpro11/YouTube-Spammer-Purge/blob/main/Linux-Installation-Instructions.md) as the wiki page for Linux Installation Instructions
> > 
> > ## Checklist:
> > 
> > * [x]   My code follows the style guidelines of this project and have read CONTRIBUTING.md
> > * [x]   I have performed a self-review of my own code
> > * [x]   I have commented on my code, particularly in hard-to-understand areas
> > * [ ]   I have made corresponding changes to the documentation
> > * [ ]   My changes generate no new warnings
> > * [ ]   I have added tests that prove my fix is effective or that my feature works
> > * [ ]   New and existing unit tests pass locally with my changes
> > * [ ]   Any dependent changes have been merged and published in downstream modules
> > * [x]   I have checked my code and corrected any misspellings
> 
> Can you please make a issue thread for this and within Fixes # mention that issue number? Thanks

Thanks for updating it, but you can see Fixes #, you gotta put the number there so remove the first line and then put:

Fixes #216

**Review by TechStudent11 — CHANGES_REQUESTED** [review]
Maybe also add an `install.bat` file for all us Windows users.

**Comment by lolpro11** [comment]
> Maybe also add an `install.bat` file for all us Windows users.

No need, as the executable should run by itself with no other required dependencies.

**Comment by joaogelado** [comment]
> > Maybe also add an `install.bat` file for all us Windows users.
> 
> No need, as the executable should run by itself with no other required dependencies.

Unless the user want to run the script, but that is not too common

**Pull request merged**
