### PR TITLE
Edit README.md

### LINKED ISSUE #220: Update screenshot
Update the opening screenshot in readme.md

### PR DESCRIPTION
**Pull request by kiatchun**
- Fixes #220 
- features more functions of the app in the "What is this" field of readme.md

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
feature more functions of the app in the "What is this" field of readme.md

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** [original screenshot ](https://user-images.githubusercontent.com/93459510/147535112-df4a745c-1d32-4497-8b98-fc541d33addb.png) | ** [Updated screenshot](https://user-images.githubusercontent.com/93459510/147535153-0d05d820-b902-4b2a-bb87-968c71f49731.png) **

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Leave space between delete and /report

I created a PR in your forked version of this, so please merge it.


Thanks,
Kendall Does Coding

**Comment by KendallDoesCoding** [comment]
@kiatchun Link to the PR: https://github.com/kiatchun/YT-Spammer-Purge/pull/2

**Comment by kiatchun** [comment]
> 
Why?

**Comment by kiatchun** [comment]
> Leave space between delete and /report
> 
> I created a PR in your forked version of this, so please merge it.
> 
> Thanks, Kendall Does Coding

Why?

**Comment by kiatchun** [comment]
> > Leave space between delete and /report
> > I created a PR in your forked version of this, so please merge it.
> > Thanks, Kendall Does Coding
> 
> Why?

I thought it is either "delete/report" or "delete / report"? (The "/" in this case means "or")

**Comment by KendallDoesCoding** [comment]
> > > Leave space between delete and /report
> > > I created a PR in your forked version of this, so please merge it.
> > > Thanks, Kendall Does Coding
> > 
> > 
> > Why?
> 
> I thought it is either "delete/report" or "delete / report"? (The "/" in this case means "or")

Oh ok. I didn't know that. I see you've reverted the changes... Thanks!

**Comment by KendallDoesCoding** [comment]
@kiatchun Can you also fix #220 in this PR, itself and in Fixes # mention #220 ??

**Comment by kiatchun** [comment]
> @kiatchun Can you also fix #220 in this PR, itself and in Fixes # mention #220 ??

Fixed

**Comment by KendallDoesCoding** [comment]
> > @kiatchun Can you also fix #220 in this PR, itself and in Fixes # mention #220 ??
> 
> Fixed

Thanks but on the first line, you can see Fixes # after the hashtag you need to put 220, and remove the line you just put for the issue to get linked.

**Comment by kiatchun** [comment]
> > > @kiatchun Can you also fix #220 in this PR, itself and in Fixes # mention #220 ??
> > 
> > 
> > Fixed
> 
> Thanks but on the first line, you can see Fixes # after the hashtag you need to put 220, and remove the line you just put for the issue to get linked.

Fixed. Again

**Comment by justkamiii** [comment]
I made a simple change/addition to this so there's no need to make a second PR, which would automatically build the project twice if it gets pushed (unnecessary for readme changes)
https://github.com/kiatchun/YT-Spammer-Purge/pull/4

**Comment by KendallDoesCoding** [comment]
> > > > @kiatchun Can you also fix #220 in this PR, itself and in Fixes # mention #220 ??
> > > 
> > > 
> > > Fixed
> > 
> > 
> > Thanks but on the first line, you can see Fixes # after the hashtag you need to put 220, and remove the line you just put for the issue to get linked.
> 
> Fixed. Again

Thanks, the issue has now been linked, perfectly.

**Comment by KendallDoesCoding** [comment]
> I made a simple change/addition to this so there's no need to make a second PR, which would automatically build the project twice if it gets pushed (unnecessary for readme changes) [kiatchun#4](https://github.com/kiatchun/YT-Spammer-Purge/pull/4)

@justkamiii Oh yeah, it adds the logo, it looks good, but can this be made small @justkamiii? I may make a PR in your forked repo

**Comment by KendallDoesCoding** [comment]
> > I made a simple change/addition to this so there's no need to make a second PR, which would automatically build the project twice if it gets pushed (unnecessary for readme changes) [kiatchun#4](https://github.com/kiatchun/YT-Spammer-Purge/pull/4)
> 
> @justkamiii Oh yeah, it adds the logo, it looks good, but can this be made small @justkamiii? I may make a PR in your forked repo

@justkamiii Done, you can merge my changes into your forked repo, @kiatchun then can merge your forked repo into this PR.

**Comment by KendallDoesCoding** [comment]
@kiatchun Also, if you merge https://github.com/kiatchun/YT-Spammer-Purge/pull/4 please edit the description saying, added the logo icon in the README or something like that.

**Comment by justkamiii** [comment]
Alrighty, I merged the PR from @KendallDoesCoding which limits the size of the image so it isn't too big
Yeah, time to wait for kiatchun to merge it and PR

**Comment by KendallDoesCoding** [comment]
> Alrighty, I merged the PR from @KendallDoesCoding which limits the size of the image so it isn't too big Yeah, time to wait for kiatchun to merge it and PR

Thanks but @ThioJoe already merged this PR, it wasn't set as a draft. @justkamiii Can you now make another PR, with your changes?

**Comment by KendallDoesCoding** [comment]
@justkamiii Don't worry about making another PR, I see @kiatchun has already done that 8 hours ago. #249

**Pull request merged**
