### PR TITLE
Add Badges

### PR DESCRIPTION
**Pull request by compsup**
# Related Issue/Addition to code
Add Badges too README.md

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

Not sure if the reason of these not being there already is that you don't want them or you just haven't done it. I personally really like when GitHub projects have informative badges, especially for test coverage and statuses of GitHub Actions. It just makes the project look more professional, and with how popular this program has gotten I feel like it is about time to do that.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
This doesn't really add anything as of such, but ig there's no hearm in adding it/Formats README a bit?

**Comment by compsup** [comment]
> This doesn't really add anything as of such, but ig there's no hearm in adding it/Formats README a bit?

Its more of a visual thing than a functional, it just looks better.

**Comment by KendallDoesCoding** [comment]
Ok, what's the difference though?

**Comment by compsup** [comment]
> Ok, what's the difference though?

it, adds badges?

**Comment by ThioJoe** [comment]
Hm ok, I just hadn't really looked into the badges before

**Pull request merged**
