### PR TITLE
build: pyproject

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
# Related Issue/Addition to code
Please delete options that are not relevant.

- Fixes #
- add pyproject config so developer can use poetry

## Type of change

Please delete options that are not relevant.

-  Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
-  Breaking change (fix or feature that would cause existing functionality to not work as expected)
-  This change requires a documentation update

# Proposed Changes
- pyproject for poetry

# Additional Info
email is copied from https://thiojoe.com/contact-me/
python version is based on poetry recommendation
to check for this pr you can run `poetry check`. i can add that to github action if needed
## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
-  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
-  New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Comment by ryleu** [comment]
You should add `poetry.lock` to `.gitignore` if it isn’t there already.

**Review by jyooru — CHANGES_REQUESTED** [review]

**Comment by jyooru** [comment]
> You should add `poetry.lock` to `.gitignore` if it isn’t there already.

Poetry suggests not to for reproducibility:

https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control

**Comment by rachmadaniHaryono** [comment]
>> You should add poetry.lock to .gitignore if it isn’t there already.

> Poetry suggests not to for reproducibility:

also on the link given

> For libraries it is not necessary to commit the lock file.

so i feel kinda conflicted about this.

 anybody who use this will get untracked poetry.lock file (but it can can locally ignored)
 
 but if there is feature to add gui like https://github.com/ThioJoe/YT-Spammer-Purge/discussions/84, poetry.lock have to be added

**Comment by ryleu** [comment]
> but if there is feature to add gui like #84, poetry.lock have to be added

Then it makes sense not to `.gitignore` it. In that case, I would recommend creating a lock file with the latest versions, testing if it works, and then committing that.

**Comment by rachmadaniHaryono** [comment]
> testing if it works, and then committing that.

as note i will add another pr to check poetry based on this https://github.com/marketplace/actions/install-poetry-action

but currently this pr only for pyproject.toml

**Comment by ThioJoe** [comment]
No clue what this is for tbh

**Comment by rachmadaniHaryono** [comment]
currently to develop this program 

- create virtual env
- `pip install -r requirements.txt`
- start development

this pr will make it easier

- `poetry install`
- start development

with poetry you can also check if package have conflicted dependency

**Review by dekoza — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
> No clue what this is for tbh

Taken the idea discussed in #42

**Review by KendallDoesCoding — COMMENTED** [review]
The bussiness email for his YT is, 
TJBusiness@thiojoe.com, but what's listed in his site is another mail which you added in this commit, Please await @ThioJoe s response on what email to use if he plans on merging this into the repo.

**Comment by rachmadaniHaryono** [comment]
for now this is the current structure of `poetry build`

```shell

> poetry build
Building YT-Spammer-Purge (2.14.2)
  - Building sdist
  - Built YT-Spammer-Purge-2.14.2.tar.gz
  - Building wheel
  - Built YT_Spammer_Purge-2.14.2-py3-none-any.whl
> tar tf dist/YT-Spammer-Purge-2.14.2.tar.gz | tree --fromfile .
.
└── YT-Spammer-Purge-2.14.2
    ├── LICENSE
    ├── PKG-INFO
    ├── Scripts
    │   ├── auth.py
    │   ├── community_downloader.py
    │   ├── files.py
    │   ├── gui.py
    │   ├── logging.py
    │   ├── operations.py
    │   ├── prepare_modes.py
    │   ├── shared_imports.py
    │   ├── utils.py
    │   └── validation.py
    ├── YTSpammerPurge.py
    ├── assets
    │   ├── SpamAccountsList.txt
    │   ├── SpamDomainsList.txt
    │   ├── SpamThreadsList.txt
    │   ├── SpamVersionInfo.json
    │   ├── cancelButton.png
    │   ├── default_config.ini
    │   ├── executeButton.png
    │   ├── icon.png
    │   ├── inputSubmitButton.png
    │   ├── inputTextBox.png
    │   ├── outputTextBox.png
    │   └── rootZoneDomainList.txt
    ├── pyproject.toml
    └── setup.py
```

**Comment by rachmadaniHaryono** [comment]
i try to add entry point like this https://python-poetry.org/docs/pyproject/#scripts

but it require to run a function

but in YTSpammerPurge.py it is hidden under `if __name__ == '__main__'` section

**Comment by ThioJoe** [comment]
Still can't figure out why this is needed and no one has explained it, let alone in the initial PR

**Comment by rachmadaniHaryono** [comment]
is this not explanation?

> currently to develop this program
> 
>     * create virtual env
> 
>     * `pip install -r requirements.txt`
> 
>     * start development
> 
> 
> this pr will make it easier
> 
>     * `poetry install`
> 
>     * start development
> 
> 
> with poetry you can also check if package have conflicted dependency
> 
> e: it also can be used in the future for packaging

**Comment by dekoza** [comment]
Poetry does several things:

- manages dependencies - and is really good at that
- manages virtual env
- manages packaging

...and it makes it all a breeze really. It's a part of modern project management.

**Pull request closed without merging**
