### PR TITLE
Improve README.md accessibility for screen readers

### PR DESCRIPTION
**Pull request by throwaway-d**
1. The "issue" and "pull request" badges are removed because they're obvious that you can already see the counters on GitHub.
2. Add height = '20' for the remaining badges. https://web.dev/optimize-cls/#images-without-dimensions
3. Improve alt texts of the badges (the alt texts on ## Screenshots is still not worked on yet)
4. Add height = '353' for the screenshots https://web.dev/optimize-cls/#images-without-dimensions
5. Remove some unnecessary trailing slashes on img elements README.md https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements

### Related Issue
- closes https://github.com/ThioJoe/YT-Spammer-Purge/issues/713

#### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project and I have read [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

---

### Screenshots

Original | Updated
:----------------------:|:-----------:
image  | image

### CODE REVIEW

**Comment by throwawayaccountfor** [comment]
I'm very newbie to GitHub and PRs. Please kindly guide me if anything's wrong. I mostly stay on Codeberg and create issues. (https://github.com/ThioJoe/YT-Spammer-Purge/discussions/994)

**Review by KendallDoesCoding — COMMENTED** [review]
> Eh i'll just keep it as is for now

The issue was closed by ThioJoe for  this. If the issue is closed NO further action needs to be taken. At the end of the day, it's ThioJoe's who decides finally.

**Comment by throwawayaccountfor** [comment]
I will try to convince him since this impacts accessibility of blind people.

**Comment by KendallDoesCoding** [comment]
> I will try to convince him since this impacts accessibility of blind people.

ok 🤷

**Comment by throwawayaccountfor** [comment]
> for now

Even he didn't really confirm that he would keep it forever. He was just procrastinating at that time.

**Comment by throwaway-d** [comment]
A good guide about alt text: https://www.w3.org/WAI/tutorials/images

**Review by KendallDoesCoding — APPROVED** [review]

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by throwaway-d** [comment]
@ThioJoe It has been many months already. Can you please merge my PR?

**Pull request merged**
