### PR TITLE
Update dockerfile to slim base image

### PR DESCRIPTION
**Pull request by djsv23**
- Fixes #
- Changing to the python:3-slim image and installing required dependencies reduces the image size from ~1GB to 377MB

# Proposed Changes
- Change base image from python:3 to python:3-slim
- Install required dependency gcc during build

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by oscrx** [comment]
Looks good, but might conflict with #467

**Comment by djsv23** [comment]
> Looks good, but might conflict with #467

I just saw that -- I'm new to contributing publicly so I'm not sure about the etiquette here, but either this can wait and rebase if #476 gets merged as-is, or we can use this PR to capture both sets of Dockerfile updates and leave #476 to the auto-build process.

**Comment by rachmadaniHaryono** [comment]
you may mean #467 instead of `#476`

**Review by EthanHindmarsh — APPROVED** [review]
Looks good to me ✅
Cutting down the size of the docker image would be great

**Comment by EthanHindmarsh** [comment]
> Looks good, but might conflict with #467

Shouldn't conflict enough to matter
Regardless of which merges first, any conflict would be easy to resolve

#467 doesn't change `FROM python:3`, and only makes the `apt` commands a single `RUN`

**Review by dada513 — APPROVED** [review]
Might wanna also use alpine to make it even smaller

**Comment by djsv23** [comment]
I tried with alpine and it actually ended up a few MB larger. I'm sure there's more tuning that could be done to trim things down further I'll explore when I have some time.

**Comment by ThioJoe** [comment]
Ok no one seems to see any issues so I'll merge

**Pull request merged**
