### PR TITLE
Fix linux installation scripts

### PR DESCRIPTION
**Pull request by Knirps1**
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

# Proposed Changes
- Removed the need to run Linux install scripts as root.
- Let pip be installed via the package managers instead of get-pip
- Install pip modules in user directory.
- Don't let pacman do a system upgrade. Not even a partial one (which can break systems).
- Check if epel-release repos are installed on centos to not remove them unwantedly.
- Run distro check prior to any installation check.
- Fixed jq removal wich removed if it was installed before and didn't if it was't installed before.

# Additional Info
- Tried using the install_full.sh script as recommended from the wiki and it didn't work. So I reworked it to work.
- Tested in Archlinux (clean chroot), Fedora 35 (fresh install), Centos 7-2009 and 8 Stream (fresh installs) and Ubuntu Server 20.04 (fresh install) worked in all tests.
- Tested only to a first run of YT-Spammer-Purge without an API key.

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by TechStudent11 — CHANGES_REQUESTED** [review]
1. Merge existing code from `ThioJoe:main` to your branch (`Knirps1:install`).
2. Have you tested it on a Debian or Ubuntu-based system?

**Comment by Firecul** [comment]
> Have you tested it on a Debian or Ubuntu-based system?

Mint is Ubuntu based iirc

> Merge existing code from `ThioJoe:main` to your branch (`Knirps1:install`).

Yeah @Knirps1, there have been changes made since your branch was created, you'll have to update your code to match.

**Comment by TechStudent11** [comment]
> > Have you tested it on a Debian or Ubuntu-based system?
> 
> Mint is Ubuntu based iirc

@Firecul I forgot that Linux Mint was Ubuntu-based. Thanks.

**Comment by Knirps1** [comment]
I'm currently working on merging the changes.

**Comment by TechStudent11** [comment]
okay

**Comment by Knirps1** [comment]
Merged the changes and updated the pull request. Will test the new versions now.

**Comment by Knirps1** [comment]
Made a crucial mistake in the version check. Fixing right now.

**Comment by Knirps1** [comment]
Made a few further fixes. Updated the pull request and tested it. Seems to work now.

**Review by compsup — APPROVED** [review]
Looks all good, taking your word for it that its successfully installs on non-arch systems. Might be nice in the future too have more information about what is being installed but thats definitely a quality of life.

**Pull request merged**
