### PR TITLE
Stylistic changes

### PR DESCRIPTION
**Pull request by kiatchun**
# Related Issue/Addition to code
Adds logo to the top of the readme.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
-Add logo to the top of the readme

# Additional Info
- any additional info for context

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Review by joaogelado — CHANGES_REQUESTED** [review]
This link will retrieve the HTML of the icon. The right link is: https://github.com/ThioJoe/YT-Spammer-Purge/raw/main/assets/icon.png

**Review by TechStudent11 — APPROVED** [review]
It's a small change but I love it.

**Comment by justkamiii** [comment]
> It's a small change but I love it.

yeee. Top-Centered logos on READMEs are the best

**Comment by ThioJoe** [comment]
hm ok

**Pull request merged**
