### PR TITLE
System to fix error of the folders

### PR DESCRIPTION
**Pull request by abhra2020-smart**
- I'll call this AutoFix 

## Type of change

- [*] New feature (non-breaking change which adds functionality)

# Proposed Changes
- Automatically fix the folders

## Checklist:

- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [*] My changes generate no new warnings
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] New and existing unit tests pass locally with my changes
- [*] Any dependent changes have been merged and published in downstream modules
- [*] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by micziz** [comment]
Decent pr, but fix the readme and dunno if will compleatly add, since some things do go againts contributing.md.

**Comment by TechStudent11** [comment]
You should change the name of this pull to be a bit more descriptive of what the program actually does.

**Comment by ThioJoe** [comment]
I'm a bit confused about the point of this. So if the os.mkdir function doesn't work, it instead uses 'md' command, but would that make a difference?

Also side note, I want to keep the note file as .txt because it can be universally opened by default, without needing to assign a program.

**Comment by EthanHindmarsh** [comment]
> I'm a bit confused about the point of this. So if the os.mkdir function doesn't work, it instead uses 'md' command, but would that make a difference?

I'm not entirely sure why this PR was made, 

`os.mkdir` calls mkdir() via C on POSIX platforms (MacOS, Linux, *BSD) and `CreateDirectoryW` on Windows,
So, for POSIX platforms, retrying with os.system(mkdir) is pointless, as it calls the same command python already had,
And for Windows, `CreateDirectoryW` is probably the same call that `md` uses, though I'm not 100% sure

The only time I could think `os.mkdir` would fail with how it is currently being called would be some edge case permission issue, in which case a retry wouldn't help any anyway

Not too sure what
> Automatically fix the folders

means either😅

Adding a README to the resource folder wouldn't be a bad idea, but it'd probably be best to just create it in the git repo and not add code to create it👍

**Comment by abhra2020-smart** [comment]
I wasn't sure if os.mkdir("x\\y")'d make folder y inside of x

**Comment by EthanHindmarsh** [comment]
I believe that's what os.makedirs(path) does

**Comment by Firecul** [comment]
> Adding a README to the resource folder wouldn't be a bad idea, but it'd probably be best to just create it in the git repo and not add code to create it👍

That I agree with.

**Comment by ThioJoe** [comment]
If this just retries creating the folders after it fails, I'm just going to pass, because presumably the same thing would cause it to happen again on retry

**Comment by abhra2020-smart** [comment]
Ok...?

**Pull request closed without merging**
