### PR TITLE
Replace long link to report bugs to short link on line 1268

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- #484 
- Python is not like HTML where you can just tap text and have the link opened in a new tab, so to make it more convenient for the user, I listed the short url to report bugs too

## Type of change
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- Replaced the github long url of the issues page with the short url

### CODE REVIEW

**Comment by EthanHindmarsh** [comment]
What?
Why not replace the long URL with the shortened one?

**Comment by KendallDoesCoding** [comment]
> What? Why not replace the long URL with the shortened one?

I was planning to do that, but for now I printed it in the next line, waiting for @ThioJoe to tell me what to do.

**Comment by EthanHindmarsh** [comment]
> > What? Why not replace the long URL with the shortened one?
> 
> I was planning to do that, but for now I printed it in the next line, waiting for @ThioJoe to tell me what to do.

I see no reason to wait 🤔 I'd just swap it out -- If he doesn't want it, he'll just deny the PR 👍
No harm no foul

**Comment by KendallDoesCoding** [comment]
> > > What? Why not replace the long URL with the shortened one?
> > 
> > 
> > I was planning to do that, but for now I printed it in the next line, waiting for @ThioJoe to tell me what to do.
> 
> I see no reason to wait 🤔 I'd just swap it out -- If he doesn't want it, he'll just deny the PR 👍 No harm no foul

True, will do it shortly.

**Comment by ThioJoe** [comment]
I'll probably just do this myself so I can format it a bit differently, I'm just keeping this open to remind me

**Comment by ThioJoe** [comment]
Added with https://github.com/ThioJoe/YT-Spammer-Purge/commit/7813b8d35278a698f36aa33e24fea2b55a270c53

**Pull request closed without merging**
