### PR TITLE
If file with extension '.json' exists

### PR DESCRIPTION
**Pull request by Panos-Jr**
If file with the extension '.json' exists (but 'client_secrets.json' doesn't), rename file to 'client_secrets.json'.
This is  ONLY if the user doesn't rename the file to 'client_secrets.json'.

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
Well, I'm 50/50 on this.

If a user downloads it in their downloads, adds the client_secrets.json file I'm still sure that would work with all their files in downloads. If a user downloads it and puts in in a drive with other json files even within folders, we dont want those .json files to be renamed client_secrets and mess up the program, but at the same time this is helpful to people so yeah I'm 50/50.

**Comment by Kurdakov** [comment]
perhaps there is need to check, that json filename contains client_secret_ and .apps.googleusercontent.com.json substrings

**Comment by Panos-Jr** [comment]
I would agree. This implementation

**Comment by Panos-Jr** [comment]
Thank you for reviewing! I can agree that this implementation is helpful from one interpretation but can be considered not from another.

**Comment by KendallDoesCoding** [comment]
@Panos-Jr You can also make it so that if there is more .json files, it will print out

JSON FILE FOUND
FILE NAMES
1.
2.
3.
Which one do you want to rename to client_secrets.json

**Comment by Panos-Jr** [comment]
````python
import os
from colorama import Fore as F, Back as B, Style as S

user = os.environ['USERPROFILE']
desktop = os.path.join(user, 'Desktop')
list_dir = os.listdir(desktop)
for dir in list_dir:
    if dir.startswith('YT'):
        print(dir)
        break

CLIENT_SECRETS_FILE = 'client_secrets.json'
file_arr = []
def select(number):
    val = number - 1
    file = file_arr[val]
    os.rename(file, CLIENT_SECRETS_FILE)

YT = os.path.join(desktop, dir)
os.chdir(YT)
num = 0
if not os.path.exists(CLIENT_SECRETS_FILE):
    LIST_DIR = os.listdir(YT) #list current directory, array.
    for dir in LIST_DIR:
        if dir.endswith('.json'):
            print(dir)
            file_arr.append(dir)
            num +=1
            print(dir)
    print(len(file_arr))

    if len(file_arr) > 1:
        print(f'{len(file_arr)} \'.json\' [FILES] were found. \n Select the file you would like to [RENAME]:')
        num1 = 1
        for file in file_arr:
            print(f'{F.MAGENTA}{S.BRIGHT}{num1}: {F.WHITE}{B.RED}\'{file}\'{B.BLACK}')
            num1 +=1
        choice = int(input(f'CHOOSE [1-{num}]: '))
        select(choice)     
    else:
        sel = input(f'RENAME: [{F.CYAN}Y/{F.RED}N{F.WHITE}]')
        if sel == 'Y' or sel == 'y':
            os.rename(dir, CLIENT_SECRETS_FILE)
        elif sel == 'N' or sel == 'n':
            print(f'{F.RED} ABORT.')
else:
    print(f'\n{F.RED}{S.DIM}FILE exists, {F.WHITE}{S.DIM}{B.RED}\'{CLIENT_SECRETS_FILE}\'{B.BLACK}')
````

**Pull request closed without merging**
