### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by Thatcooldevguy**
# Things Added/Fixed:
- Fixed lots of wonky spaces when it came to logging
- Used more color to express error messages or messsages that needed the users attetnion.
- Removed extra -'s that caused menus and errors to look bad/weired (if I missed any, let me know)
- Added handling for githubs ratelimiting + non 200 status codes in the update function
- Removed U-3 as the fectcher for errors now outputs it own.
- Added an autoupdater for windows, also displays a nice progress bar using the tqdm module.
- Added tqdm for autoupdater 
- Added a stopwatch to the scanning phase.
- Added clear commands to ln 2185 and 2188 to make the menus look better
- Reworded some errors.

# Bugs Found: 
oauthlib.oauth2.rfc6749.errors.AccessDeniedError: (access_denied) is thrown when you logout (answer n to is this account correct), attempt to reauth, and cancel. I don't know how to catch it (because it should 
as we call the same function). Ideas on catching?

# Questions:
On line 1382, we check if we are a windows system for the autoupdater. As of now, there is no "file" to download for macos/linux. 
Could we also add like for example YTSpammerPurge.2.4.2_macos_and_linux.zip so the updater works on linux?

Also, I emailed joe about this, but is there a discord where this project is being ran on/supported or is there a main discord for joe's channel.

# Screenshots:

stopwatch: 
https://img.sticks.network/0NkthLrsg

New Menu Layouts:
https://img.sticks.network/MMVqWtTga
https://img.sticks.network/46u603UmK

Examples of new logging:
https://img.sticks.network/YwIvfJ5wx
https://img.sticks.network/svschPM8f

Autoupdater:
https://img.sticks.network/mmmiy7ZOc

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Proposed Changes
This commit purposes the following:
 - Fixing the broken wording of some errors/logs
 - Adding better logs
 - Adding an autoupdater
 - Reformatting menus
This is a general overview. See the Things Added/Fixed section for what I did.

# Additional Info
N/A

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Thatcooldevguy** [comment]
@ThioJoe Would like your review on this please.

**Comment by kiatchun** [comment]
Will the documentation change just be because of the colours?

**Comment by Thatcooldevguy** [comment]
> Will the documentation change just be because of the colours?

Was not for sure

**Comment by ThioJoe** [comment]
One thing I'll have to make sure of is that Windows won't default to blocking the downloading of the exe file

**Comment by Thatcooldevguy** [comment]
> One thing I'll have to make sure of is that Windows won't default to blocking the downloading of the exe file

Did not for me with win11x64 running malwarebytes and windefend

**Comment by ThioJoe** [comment]
There's definitely a lot of good stuff in here, I'll merge it into a branch just so I can tweak a few things before merging it to main

**Comment by Thatcooldevguy** [comment]
was pr250 ever added to main @ThioJoe ?

**Pull request merged**
