### PR TITLE
Make get latest release on beta channel 

### PR DESCRIPTION
**Pull request by joaogelado**
# Related Issue/Addition to code
Please delete options that are not relevant.

- Issue/Addition to code, goes here.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Proposed Changes
- If you make a release after a beta release, it will get the latest **beta** release

# Additional Info
- I couldn't test it

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by ThioJoe** [comment]
Ah good idea. I'll have to test this heavily first. A bug in the update system would be basically the worst possible bug because people wouldn't even know about updates

**Comment by joaogelado** [comment]
ok no problem

**Comment by joaogelado** [comment]
one thing I can add is if you release beta 2 before beta 1, it would get the beta 2, but I don't think this would happen. If you think this can happen, you can delete the `break` in line 182 to exit the loop

**Comment by joaogelado** [comment]
yeah I think this is dead...

**Comment by EthanHindmarsh** [comment]
> yeah I think this is dead...

🤷 I'd just leave it open, no reason to close

**Comment by ThioJoe** [comment]
Not dead, it's just I'm not going to merge this until I'm working on the next feature release 2.17, so it would go into the beta branch

**Comment by ThioJoe** [comment]
Coming back to this with some new info. So I recently released 2.16.10 after having released 2.17.0 Betas 1 and 2. The request response actually still seems to return the pre-releases at the top: https://api.github.com/repos/ThioJoe/YT-Spammer-Purge/releases

**Pull request merged**
