### PR TITLE
If ‘client_secrets.json’ doesn’t exist, but a ‘.json’ file does exist.

### PR DESCRIPTION
**Pull request by Panos-Jr**
If a ‘.json’ file exists without the file name ‘client_secrets.json’ (in the current directory), rename it to ‘client_secrets.json’. If ‘.json’ files are existent, they will not be renamed.

`My modifications`
````python 
num = 0
file = None
if not os.path.exists(CLIENT_SECRETS_FILE):
  CURR_DIR = os.path.dirname(os.path.realpath(__file__))
  LIST_DIR = os.listdir(CURR_DIR) #list current directory, array.
  for dir in LIST_DIR:
      if dir.endswith('.json'):
        print('\n exists')
        file = dir
        num +=1
   if num < 2:
     os.rename(file, CLIENT_SECRETS_FILE)
   else:
     print(f"\n         ----- {F.WHITE}{B.RED}[!] Error:{S.R} client_secrets.json file not found -----")
     print(f" ----- Did you create a {F.YELLOW}Google Cloud Platform Project{S.R} to access the API? ----- ")
     print(f"  > For instructions on how to get an API key, visit: {F.YELLOW}www.TJoe.io/api-setup{S.R}")
     print(f"\n  > (Non-shortened Link: https://github.com/ThioJoe/YT-Spammer-Purge#instructions---obtaining-youtube-api-key)")
     input("\nPress Enter to Exit...") 
     sys.exit()

````

`Original`
````python
if not os.path.exists(CLIENT_SECRETS_FILE):
  print(f"\n         ----- {F.WHITE}{B.RED}[!] Error:{S.R} client_secrets.json file not found -----")
  print(f" ----- Did you create a {F.YELLOW}Google Cloud Platform Project{S.R} to access the API? ----- ")
  print(f"  > For instructions on how to get an API key, visit: {F.YELLOW}www.TJoe.io/api-setup{S.R}")
  print(f"\n  > (Non-shortened Link: https://github.com/ThioJoe/YT-Spammer-Purge#instructions---obtaining-youtube-api-key)")
  input("\nPress Enter to Exit...") 
  sys.exit()

````

### CODE REVIEW

**Comment by ThioJoe** [comment]
I'm not sure if I'd want to implement something like this, because some users might have multiple json files for multiple google cloud projects. It's also been suggested to add a 'project switching' feature to work around the API quota

**Comment by Panos-Jr** [comment]
Thank you for reviewing, ThioJoe!

**Comment by Panos-Jr** [comment]
@ThioJoe Consider this implementation (@KendallDoesCoding Suggested this)

 import os
from colorama import Fore as F, Back as B, Style as S

user = os.environ['USERPROFILE']
desktop = os.path.join(user, 'Desktop')
list_dir = os.listdir(desktop)
for dir in list_dir:
    if dir.startswith('YT'):
        print(dir)
        break

CLIENT_SECRETS_FILE = 'client_secrets.json'
file_arr = []
def select(number):
    val = number - 1
    file = file_arr[val]
    os.rename(file, CLIENT_SECRETS_FILE)

YT = os.path.join(desktop, dir)
os.chdir(YT)
num = 0
if not os.path.exists(CLIENT_SECRETS_FILE):
    LIST_DIR = os.listdir(YT) #list current directory, array.
    for dir in LIST_DIR:
        if dir.endswith('.json'):
            print(dir)
            file_arr.append(dir)
            num +=1
            print(dir)
    print(len(file_arr))

    if len(file_arr) > 1:
        print(f'{len(file_arr)} \'.json\' [FILES] were found. \n Select the file you would like to [RENAME]:')
        num1 = 1
        for file in file_arr:
            print(f'{F.MAGENTA}{S.BRIGHT}{num1}: {F.WHITE}{B.RED}\'{file}\'{B.BLACK}')
            num1 +=1
        choice = int(input(f'CHOOSE [1-{num}]: '))
        select(choice)     
    else:
        sel = input(f'RENAME: [{F.CYAN}Y/{F.RED}N{F.WHITE}]')
        if sel == 'Y' or sel == 'y':
            os.rename(dir, CLIENT_SECRETS_FILE)
        elif sel == 'N' or sel == 'n':
            print(f'{F.RED} ABORT.')
else:
    print(f'\n{F.RED}{S.DIM}FILE exists, {F.WHITE}{S.DIM}{B.RED}\'{CLIENT_SECRETS_FILE}\'{B.BLACK}')
#Authors : Panos-Jr and KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> @ThioJoe Consider this implementation (@KendallDoesCoding Suggested this)
> 
> The user will be asked for which file they would like to rename.
> 
> ```python
> import os
> from colorama import Fore as F, Back as B, Style as S
> 
> user = os.environ['USERPROFILE']
> desktop = os.path.join(user, 'Desktop')
> list_dir = os.listdir(desktop)
> for dir in list_dir:
>     if dir.startswith('YT'):
>         print(dir)
>         break
> 
> CLIENT_SECRETS_FILE = 'client_secrets.json'
> file_arr = []
> def select(number):
>     val = number - 1
>     file = file_arr[val]
>     os.rename(file, CLIENT_SECRETS_FILE)
> 
> YT = os.path.join(desktop, dir)
> os.chdir(YT)
> num = 0
> if not os.path.exists(CLIENT_SECRETS_FILE):
>     LIST_DIR = os.listdir(YT) #list current directory, array.
>     for dir in LIST_DIR:
>         if dir.endswith('.json'):
>             print(dir)
>             file_arr.append(dir)
>             num +=1
>             print(dir)
>     print(len(file_arr))
> 
>     if len(file_arr) > 1:
>         print(f'{len(file_arr)} \'.json\' [FILES] were found. \n Select the file you would like to [RENAME]:')
>         num1 = 1
>         for file in file_arr:
>             print(f'{F.MAGENTA}{S.BRIGHT}{num1}: {F.WHITE}{B.RED}\'{file}\'{B.BLACK}')
>             num1 +=1
>         choice = int(input(f'CHOOSE [1-{num}]: '))
>         select(choice)     
>     else:
>         sel = input(f'RENAME: [{F.CYAN}Y/{F.RED}N{F.WHITE}]')
>         if sel == 'Y' or sel == 'y':
>             os.rename(dir, CLIENT_SECRETS_FILE)
>         elif sel == 'N' or sel == 'n':
>             print(f'{F.RED} ABORT.')
> else:
>     print(f'\n{F.RED}{S.DIM}FILE exists, {F.WHITE}{S.DIM}{B.RED}\'{CLIENT_SECRETS_FILE}\'{B.BLACK}')
> #Authors : Panos-Jr and KendallDoesCoding
> ```

Yes, according to me this would be much better because it just werent randomly name a file, But I also think this is a useful feature.

**Pull request closed without merging**
