### PR TITLE
Add banner in README

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- Added banner to README

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Proposed Changes
- Added banner
- Remove badges which are duplicate, in banner

# Additional Info
- @ThioJoe you can customize the design of the banner etc on this site: https://socialify.git.ci/

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
Unfortunately, unlike the badges the minimum time it takes to update the details is around 10 minutes, but it looks very cool!

**Review by EthanHindmarsh — COMMENTED** [review]
Don't know if I love it, checking out how it would look on mobile (attached) doesn't look too great to me - If you want to see yourself see how to use [device mode in chrome dev tools here](https://developer.chrome.com/docs/devtools/device-mode/)
image

**Comment by KendallDoesCoding** [comment]
> Don't know if I love it, checking out how it would look on mobile (attached) doesn't look too great to me - If you want to see yourself see how to use [device mode in chrome dev tools here](https://developer.chrome.com/docs/devtools/device-mode/) image

In my opinion this looks good too!

**Comment by ThioJoe** [comment]
Doesn't look bad but I'd rather not push the readme info further down the page

**Comment by KendallDoesCoding** [comment]
> Doesn't look bad but I'd rather not push the readme info further down the page

You can make the banner small :)

**Pull request closed without merging**
