### PR TITLE
Added option to start again

### PR DESCRIPTION
**Pull request by TechStudent11**
# Related Issue/Addition to code

- Issue/Addition to code, goes here.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Proposed Changes
- At the end of each execution of the program, it asks if the user would like to go again. I think this feature has been heavily requested.

# Additional Info
- Nope

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by TechStudent11** [comment]
@ThioJoe I thought about putting it in the main function, however it was so damn messy that I decided to put it at the bottom.

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Wow, this is cool and interesting!

**Comment by KendallDoesCoding** [comment]
@TechStudent11 I modified the text, asking if the user wants to run the program again, please check https://github.com/TechStudent11/YouTube-Spammer-Purge/pull/2

**Comment by KendallDoesCoding** [comment]
image

??

**Comment by TechStudent11** [comment]
Uhhhhhh. IDK what that specifically means, that I think that on line 1192 it's asking to put either `https://` or `http://` at the beginning of `youtube.com`.

**Comment by KendallDoesCoding** [comment]
I'll have a look at that line and see if I find anything useful to that
error.

**Comment by KendallDoesCoding** [comment]
It's within this

  # Validate each ID in list
  for i in range(len(inputList)):
    valid, IDList[i], channelTitle = validate_channel_id(inputList[i])
    if valid == False:
      print(f"{B.RED}{F.BLACK}Invalid{S.R} Channel ID or Link: " + str(inputList[i]) + "\n")
      return False, None
  
  return True, IDList

@ThioJoe is this error a big deal? We didnt make any changes to this so its weird how the error is showing in this PR??

**Comment by ThioJoe** [comment]
I'm going to implement this a different way so no real need to worry more about it

**Pull request closed without merging**
