### PR TITLE
Fix for #604

### LINKED ISSUE #604: [Bug]: Update failed and deleted all files in current directory
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to perform the self-update from 2.15.0 to 2.15.1 on Linux, but the update failed and apparently performed a self-destruct (the entire current directory was emptied out, including client secrets, config, and the software itself).

Might have been a one-off. I haven't had time to re-install and re-test it.

### Release version

2.15.0

### Steps to reproduce

1. Start ./YTSpammerPurge.py
2. Use option 9 to trigger a self-update and confirm with 'Yes'.

Result: All files in the current directory are deleted.

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
`Getting info about latest updates...
------------------------------------------------------------------------------------------
 A new version is available! Visit TJoe.io/latest to see what's new.
   > Current Version: 2.15.0
   > Latest Version: 2.15.1
------------------------------------------------------------------------------------------

Update Now? (y/n): 
> Downloading version: 2.15.1

> Extracting...
> Installing...
Traceback (most recent call last):
  File "/home/steltek/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 1612, in <module>
  File "/home/steltek/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 1589, in main
  File "/home/steltek/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 875, in primaryInstance
  File "/home/steltek/YT-Spammer-Purge-2.15.0/Scripts/files.py", line 356, in check_for_update
FileNotFoundError: [Errno 2] No such file or directory: '/home/steltek/YT-Spammer-Purge-2.15.0/temp/YT-Spammer-Purge-2.15.1'
------------------------------------------------
Error Message: [Errno 2] No such file or directory: '/home/steltek/YT-Spammer-Purge-2.15.0/temp/YT-Spammer-Purge-2.15.1'

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
steltek@shodan:~/YT-Spammer-Purge-2.15.0$ ./YTSpammerPurge.py 
bash: ./YTSpammerPurge.py: No such file or directory
steltek@shodan:~/YT-Spammer-Purge-2.15.0$ ls -l
total 4
drwxr-xr-x 2 steltek steltek 4096 Feb  8 11:35 temp
steltek@shodan:~/YT-Spammer-Purge-2.15.0$ `
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by compsup**
Fixes #604

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
## Checklist:

- [X] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by compsup** [comment]
I have tested this however could someone who uses Linux also test it just to make sure. Never know if something quirky made it work.

**Comment by ThioJoe** [comment]
So this only transfers over client_secrets.json and token.pickle and deletes everything else? If so that isn't how it should be done. For example that would delete any ini config files, and the 'configs' folder that will be in 2.16.

I think it would make more sense to specify the files that will be upgraded and need to be overwritten, which is pretty consistent. It would be anything in the assets folder, the main script, and the Scripts folder, the requirements file, and i guess the docker yml files.

I'd much rather have it mess up by forgetting to delete something than deleting something it shouldn't

**Comment by compsup** [comment]
> So this only transfers over client_secrets.json and token.pickle and deletes everything else? If so that isn't how it should be done. For example that would delete any ini config files, and the 'configs' folder that will be in 2.16.
> 
> I think it would make more sense to specify the files that will be upgraded and need to be overwritten, which is pretty consistent. It would be anything in the assets folder, the main script, and the Scripts folder, the requirements file, and i guess the docker yml files.
> 
> I'd much rather have it mess up by forgetting to delete something than deleting something it shouldn't

Have too admit never thought about going about it that way. I will rewrite it to do that.

**Comment by ThioJoe** [comment]
In that case it could just copy each file out of the tar file / staging folder, and overwrite it's counterpart in the current directory. That way it would only touch the actual program files, and not anything that was generated afterwords. Definitely don't see the need to delete everything in the folder.

**Pull request merged**
