### PR TITLE
Linux Auto-Updater

### PR DESCRIPTION
**Pull request by compsup**
## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

- [X] This change requires a documentation update

# Proposed Changes
- auto-updater for linux

# Additional Info
- Currently this auto-updater does not download from GitHub releases but instead directly using 'git pull'
- Does not support the beta version due to not supporting GitHub releases

## Checklist:

- [X] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Kurdakov** [comment]
in fact code to get latest release is already  in install*.sh, it needs to be ported to python the same way update made for windows, so it is welcome addition, but somewhat looks like not a feature utility needs (besides git might not be installed on non development linux machine)

**Comment by Kurdakov** [comment]
in fact code to get latest release is already  in install*.sh, it needs to be ported to python the same way update made for windows, so it is welcome addition, but somewhat looks like not a feature utility needs (besides git might not be installed on non development linux machine)

**Comment by compsup** [comment]
Never thought about that, I will close this and open another one with a very more simplified version using the .tar.gz file.

**Comment by Firecul** [comment]
I've also came across the problem of pulling commits mid-release so the program doesn't work correctly, using the tar.gz would skip that problem.

**Pull request closed without merging**
