### PR TITLE
fix: boolean conventions and few others

### PR DESCRIPTION
**Pull request by Destroid1669**
- Fixes #
- Boolean conventions
- for loop optimization

## Type of change
Python uses `is` for checking explicitly None, True and False whereas `==` is
used to compare values not using this convention correctly may result in hard to track bugs.
for e.g: 
```py
>>> 1 == True
True
```
# Proposed Changes
- Boolean conventions
- enumerate usage
- replaced generator object which were further
- converted into list with list comprehension
- used `_` for non used variables.

# Additional Info
- enumerate function can be used for retrieving both
- index and element from an iterable.
- checkout below link for a quick look
https://github.com/Destroid1669/Python_functions_and_methods/blob/b1f72c4c25ba5d6a924f80314ddcd4a0dbf9f5be/built_in_functions.py#L287

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by EthanHindmarsh** [comment]
List comprehension fixes look great 👍
I don't see anything that would cause issue, so LGTM✅

**Comment by ThioJoe** [comment]
Bruh, contributing guidelines

**Comment by Destroid1669** [comment]
I read contributing guidelines, what's wrong, did I miss something ?

**Comment by Destroid1669** [comment]
if it's what you think then it's alright, I submitted this fix because that convention is generally discouraged in python specially in development, because it can lead to hard to debug bugs since unlike other programming languages python comparison operators acts differently.

**Comment by notoriousjere** [comment]
So sad to see such a great PR die. Code style and universally agreed upon Python conventions matter ThioJoe!

**Pull request closed without merging**
