### PR TITLE
auto assign thiojoe to review pr

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- Auto-assign @ThioJoe as a PR reviewer

## Type of change
- [ ] This change requires a documentation update

# Proposed Changes
- Added code-owners file
- Made it so that ThioJoe will automatically be assigned as a reviewer for PR's in this repo.

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
I think github removed this feature. But, I'm still doing research to confirm.

**Comment by kiatchun** [comment]
This will be nice.

**Comment by KendallDoesCoding** [comment]
> This will be nice.

Yeah, but as mentioned I think github got rid of this feature.

**Comment by KendallDoesCoding** [comment]
@ThioJoe Actually, merge this and let's see if it works or no.

**Comment by KendallDoesCoding** [comment]
Yeah, @ThioJoe It should work. I found this interesting article - https://stackoverflow.com/questions/61903008/codeowners-file-in-github-repo-not-working.

I was doing testings on my own repo, and because I am the owner of the repo, I cannot request a review from myself, that's why there's no option to request a review. So this ideally should work, if I or any other user makes a PR in this repo. So, feel free to merge this.

Thanks,
Kendall Does Coding

**Comment by KendallDoesCoding** [comment]
@ThioJoe Also, let me know if I should set the directory of YT-Spammer-Purge/.github/ISSUE_TEMPLATE/ to auto-assign @TechStudent11 cause he was the one who coded the templates, or if it should remain as it is.

You can also let me know if you want any other users to be assigned to PR's of a specific path, but for now I think by you only being assigned to PR's in the full project will be good cause you know everything as it is your project.

**Comment by KendallDoesCoding** [comment]
I did a test with a alt account, and yes it works. It's auto-assigning me to the PR on my repo.

**Comment by ThioJoe** [comment]
It doesn't really make a difference since I'm the only maintainer, and it would just be one more email notification showing up

**Comment by KendallDoesCoding** [comment]
Yeah, but I just thought it would be a nice touch. But I forgot about the
email notifications lol

**Pull request closed without merging**
