### PR TITLE
refactor install script

### PR DESCRIPTION
**Pull request by Ahummeling**
I'm not really sure if such a contribution would be welcomed, please let me know if this install scripts are not to be touched.
Would be happy to discuss any issues found with this PR and please let me know if there's anything I can do to improve my changes.

## Type of change
- [x] Bug fix 

# Additional Info
I tried to achieve several things with this PR:
 - reduce code duplication in the 2 installer scripts (notably, `install.sh` isn't even mentioned anymore in the documentation)
 - ensure all the required dependencies are installed 
 - add support for alpine
After having rewritten the installer script, I have tested it against every distro that is supported and from this process figured out any missing dependencies.
Additionally, I think unit tests do no apply for these type of changes, but I might be wrong. If unit tests apply here, please point me in the right direction and I will figure it out!

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by dekoza** [comment]
These scripts should be removed in favor of installing this from pypi  -> `pip install yt-spam-purger` or smth.

**Comment by Ahummeling** [comment]
Completely agreed tbh

**Review by compsup — CHANGES_REQUESTED** [review]
There really should only be one install.sh not two. Keep the full install and the minimal install just maybe make it ask when you run the script.

**Comment by ThioJoe** [comment]
So you don't think it's ready yet?

**Comment by compsup** [comment]
> So you don't think it's ready yet?

Correct, there should only be one `install.sh` file and it should ask if you want to do a minimal or full install.

**Comment by Firecul** [comment]
> There should be no install script and the tool should be installable using pip 😉

#42 and #515 have suggested that already @dekoza , I don't entirely disagree but I don't mind which myself.

**Comment by lolpro11** [comment]
> There really should only be one install.sh not two. In the single file make it ask if you want to do a full or minimal install.

The `install.sh` was for installing dependencies, while the `install_full.sh` was for installing dependencies + a copy of YT-Spammer-Purge.

**Comment by Ahummeling** [comment]
I think the changes would still leave the behavior as @lolpro11 is describing it, but only with support for more operating systems. I completely agree that the end-goal should be to have this tool installed via pip, not a bash script. But I think it then leaves a decision to be made, should this be merged the way it is or should I refactor this to a single install script or do we close the PR?

**Comment by micziz** [comment]
So basallcy #668 reafactors install.sh into one script, depending on platform

**Comment by Ahummeling** [comment]
oh that looks much better already. I think this PR can be closed.

**Comment by micziz** [comment]
Up to you, but tecniccly your pr inspired #664 witch then inspired #668 so this wasn't ussless.

**Comment by Ahummeling** [comment]
Glad to have inspired others!
I don't think it was useless at all, so all good :)

**Comment by micziz** [comment]
👍

**Pull request closed without merging**
