### PR TITLE
link to file instead of wiki for linux setup

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- There is a Linux-Installation-Instructions.md with more info then the wiki, but the link to "Linux Setup" is to the wiki.

## Type of change
- [ ] This change requires a documentation update

# Proposed Changes
- Updated path to go to file instead of wiki

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@ThioJoe Also, if the wiki is in place I don't understand the need of that file, @lolpro11 Can't edit the wiki. I think you copy that file into the wiki and get rid of this file, and close this PR.

If there's another purpose to this file though, you can keep it and merge this PR in.

**Comment by Kurdakov** [comment]
there needs change to install.sh https://github.com/ThioJoe/YT-Spammer-Purge/discussions/305 because it loads old version 
(sorry just not very versed in pull requests to make my own)

**Comment by KendallDoesCoding** [comment]
> there needs a change in install.sh #305 because it loads old version (sorry just not very versed in pull requests to make my own)

Oh, So should I close this while that is being worked on?

**Comment by Kurdakov** [comment]
Maybe you might add needed changes and check they work and then have a pull request?

**Comment by KendallDoesCoding** [comment]
> Maybe you might add needed changes and check they work and then have a pull request?

I think its best that @lolpro11 adds #305 because, I don't use Linux nor understand .sh files and may mess up something, but for now is the file functional or no?

**Comment by Kurdakov** [comment]
yes sh  file is functional

**Comment by ThioJoe** [comment]
Yea I've ended up just moving everything from the `Linux-Installation-Instructions.md` into the wiki page for linux. I'll just delete the file.

**Pull request closed without merging**
