### PR TITLE
optimize for loop in operations.py

### PR DESCRIPTION
**Pull request by virophagesp**
the order of the list it is iterating over does not matter

Why is this change needed:
it reduces latency for reply scanning

Additional Info:
the for loop doesnt require a proper order

Checklist:
- [x] My code follows the style guidelines of this project and I have read [CONTRIBUTING.md](https://github.com/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by virophagesp** [comment]
how do i check the boxes

**Comment by virophagesp** [comment]
nevermind i figured it out

**Comment by virophagesp** [comment]
@ThioJoe this is ready to be checked

**Comment by ThioJoe** [comment]
Isn't this made redundant by line 744?

**Comment by virophagesp** [comment]
not exactly, line 744 prevents it going through if it never had the @ symbol in the first place
line 749 modifies the original commentText variable
allThreadAuthorNames can be very long 
usually here is only a single @ username
when commentText gets modified to no longer have any @'s my code breaks out of the loop

**Comment by virophagesp** [comment]
I am going to benchmark the code and find how much of an improvement it is

**Comment by virophagesp** [comment]
so turns out it is less than 0.05% in most cases
I did the original benchmark wrong
I'm gonna close this now

**Pull request closed without merging**
