### PR TITLE
Losslessly compress icons

### PR DESCRIPTION
**Pull request by Oondanomala**
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Proposed Changes

Losslessly optimize all assets.

Not sure how to deal with the ones on the readme.

# Additional Info

Shouldn't change anything aside from file size

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
Looks much better.

**Comment by KendallDoesCoding** [comment]
@Oondanomala But, why does the size need to be small? You made it a slight less number and the size on disk is anyway 4KB, @ThioJoe 's size is 4.5 and size on disk I think is 5KB

**Comment by KendallDoesCoding** [comment]
True, it will save project space. But, let @ThioJoe decide on this one.

**Review by TechStudent11 — COMMENTED** [review]
- Doesn't affect functionality of program
- But eh it's fine

**Review by KendallDoesCoding — COMMENTED** [review]
I didn't understand this PR in my previous review.

This is a harmless PR, I guess it does save file space but only by a tiny bit.

**Review by compsup — APPROVED** [review]
I don't see why not too merge, it is useful, even if only a little bit, and @Oondanomala went through the process of doing it and it doesn't harm anything.

**Comment by KendallDoesCoding** [comment]
> I don't see why not too merge, it is useful, even if only a little bit, and @Oondanomala went through the process of doing it and it doesn't harm anything.

Yup that's true. @Oondanomala did go through the process and did a great job actually.

**Comment by TechStudent11** [comment]
> I don't see why not too merge, it is useful, even if only a little bit, and @Oondanomala went through the process of doing it and it doesn't harm anything.

That is true, yeah.

**Comment by Oondanomala** [comment]
I have optimized them further using more heavy compression ([zopfli](https://github.com/google/zopfli)).
This shouldn't change anything aside from saving a few more bytes

**Review by TechStudent11 — APPROVED** [review]
LGTM ✔️

Once again, saves a few bytes, doesn't change the actual functionality of the program. But as someone who constantly gets "Low on space" warnings and errors on my computer this is actually really useful because even a few bytes count.

**Comment by KendallDoesCoding** [comment]
> I have optimized them further using more heavy compression ([zopfli](https://github.com/google/zopfli)). This shouldn't change anything aside from saving a few more bytes

Thanks

**Comment by ThioJoe** [comment]
Tbh I had a bunch of trouble with macOS not liking the encoding of certain images so I don't think I want to mess with them just for a few bytes

**Pull request closed without merging**
