### PR TITLE
I cleaned this up a bunch

### PR DESCRIPTION
**Pull request by UP929312**
Should be easier to read, more memory and cpu efficient

## Type of change

Please delete options that are not relevant.

- [x] Refactor

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by meesyice** [comment]
What do you have against the filter function?

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by ThioJoe** [comment]
bruh read the contributing guidelines
https://github.com/ThioJoe/YT-Spammer-Purge/blob/main/CONTRIBUTING.md

**Comment by UP929312** [comment]
Ah, fair play, I didn't see those. That's on me.

But can I ask why?
It's better to be maintained, easier to read, and if this is going to be as big as we all hope it is, it's just better in general.
I can't really see a reason *not* to improve the code..

**Comment by UP929312** [comment]
> What do you have against the filter function?

The creator from Python even said they shouldn't be used (most of the time), same with map and reduce, they're not very Pythonic and generally supposed to be avoided (hence why some of those kinds of functions were removed from the standard library)

**Comment by KendallDoesCoding** [comment]
> Ah, fair play, I didn't see those. That's on me.
> 
> But can I ask why? It's better to be maintained, easier to read, and if this is going to be as big as we all hope it is, it's just better in general. I can't really see a reason _not_ to improve the code..

Well, but it is fine as it is, so why add it when its not needed lol, and I didnt get what you did exactly so I approved this PR, sorry!

**Comment by dekoza** [comment]
ThioJoe: Hey YouTube, got some improvements for ya.
YouTube: bruh, we're fine.

Pro Pythonista: Hey ThioJoe, got some improvements for ya.
ThioJoe: bruh, I'm fine.

:shrug:

**Comment by UP929312** [comment]
> ThioJoe: Hey YouTube, got some improvements for ya. YouTube: bruh, we're fine.
> 
> Pro Pythonista: Hey ThioJoe, got some improvements for ya. ThioJoe: bruh, I'm fine.
> 
> 🤷

Tell me about it

**Pull request closed without merging**
