### PR TITLE
Reduce Youtube API Quota usage

### PR DESCRIPTION
**Pull request by Bearddyy**
# Related Issue/Addition to code

- Fixes #
- Reduce youtube API Quota Usage

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Proposed Changes

# Additional Info
- The YouTube Quota usage is listed here: https://developers.google.com/youtube/v3/determine_quota_cost, The cost for a youtube "search" is "100" Quota, whereas fetching the Channel resource and then the channels "uploads" Playlist are 1 each.  This should, in theory, reduce quota usage by a lot allowing people to scan more videos/comments. Its possible the Channel resource only needs fetching once but I wasn't sure how this project implements persistent data and may be open to more bugs so left the interfaces as they were.  

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
> I would appreciate anyone able to test this on some other channels to confirm the uploads playlist is working correctly.

You didn't test it?

**Comment by Bearddyy** [comment]
> > I would appreciate anyone able to test this on some other channels to confirm the uploads playlist is working correctly.
> 
> You didn't test it?

I have tested it, on my machine, on a set of YouTubers I follow, but this is still a fairly small test case.

**Review by EthanHindmarsh — APPROVED** [review]
based, LGTM ✅

**Comment by KendallDoesCoding** [comment]
> > > I would appreciate anyone able to test this on some other channels to confirm the uploads playlist is working correctly.
> > 
> > 
> > You didn't test it?
> 
> I have tested it, on my machine, on a set of YouTubers I follow, but this is still a fairly small test case.

Oh ok.

I said this on email, don't know why it didn't show up here.

**Review by KendallDoesCoding — APPROVED** [review]
great idea! LGTM ✔️

**Comment by kdybicz** [comment]
I don't want to rush you guys, but if this is working I would appreciate a release. I'm using your tool for flagging spam and scam on UA fighters channels, like: https://www.youtube.com/c/StarskyUA If you need help with testing, let me know ;)

**Comment by ThioJoe** [comment]
> I don't want to rush you guys, but if this is working I would appreciate a release. I'm using your tool for flagging spam and scam on UA fighters channels, like: https://www.youtube.com/c/StarskyUA If you need help with testing, let me know ;)

This would go into the next major release version but I haven't started working that. Assuming it works I'd suggest just running the python script version from the fork of the pull request so you can use it

**Comment by Bearddyy** [comment]
> I don't want to rush you guys, but if this is working I would appreciate a release. I'm using your tool for flagging spam and scam on UA fighters channels, like: https://www.youtube.com/c/StarskyUA If you need help with testing, let me know ;)

If you wish to run it you can check it our here: https://github.com/Bearddyy/YT-Spammer-Purge  
It will save you enough Quota to scan 98 more comments on a channel or like 49 comments scanned the deleted, roughly.  
  
If it works please comment back here to that effect so ThioJoe will know if/whenever it gets merged.

**Comment by kdybicz** [comment]
Tested on channel with 227 videos.

Summary of first scan - Old approach:
Total: [89577/94706] (95%) | Comments Scanned: 40693 | Replies Scanned: 48884 | Matches Found So Far: 81

Summary of second scan - New approach:
Total: [89601/94771] (95%) | Comments Scanned: 40740 | Replies Scanned: 48861 | Matches Found So Far: 81

Quota cost taken from: https://developers.google.com/youtube/v3/determine_quota_cost

|API call | Old approach|New approach|Quota Cost|Old approach cost|New approach cost|
| ------ | -----: | -----: | -----: | -----: | -----: |
|youtube.api.v3.V3DataChannelService.List|5|10|1|5|10|
|youtube.api.v3.V3DataCommentService.List|3453|3465|1|3453|3465|
|youtube.api.v3.V3DataCommentService.MarkAsSpam|4|4|50|200|200|
|youtube.api.v3.V3DataCommentThreadService.List|523|525|1|523|525|
|youtube.api.v3.V3DataPlaylistItemService.List|0|5|1|0|5|
|youtube.api.v3.V3DataSearchService.List|5|0|100|500|0|
|youtube.api.v3.V3DataVideoService.List|227|227|1|227|227|

| |Old approach cost|New approach cost|
| ------ | -----: | -----: |
|Total Cost|4908|4432|
|Difference in Cost||-476|

**Comment by TechStudent11** [comment]
So basically, the new approach uses more quota instead of less?

**Comment by kdybicz** [comment]
> So basically, the new approach uses more quota instead of less?

No, new approach uses 476 of quota less in my test scenario.

**Comment by ThioJoe** [comment]
I'll put this into the new Dev branch I've created

**Comment by KendallDoesCoding** [comment]
Oh ok, makes sense.

**Pull request merged**
