### PR TITLE
test YTSpammerPurge

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
# Related Issue/Addition to code
Please delete options that are not relevant.

- Fixes #
- Issue/Addition to code, goes here.

basic test for every module with pytest

## Type of change

Please delete options that are not relevant.

-  Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
-  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Proposed Changes
basic test for almost every module with pytest

# Additional Info
require pytest

see also comments below

## modules

- [x] YTSPammerPurge
- Scripts
  - [x] auth
  - [x] community_downloader
  - [x] files
  -  gui
  - [x] logging
  - [x] operations
  - [x] prepare_modes
  -  shared_imports
  - [x] utils
  - [x] validation

## how to test

- add my repo to remote

```shell
> git remote add rh https://github.com/rachmadaniHaryono/YT-Spammer-Purge.git
```

- fetch remote

```shell
> git fetch --all
```

- checkout this pr

```shell
> git checkout rh/feature/test-upstream
```

### with poetry 

- checkout pyproject.toml

```shell
> git checkout rh/feature/pyproject -- pyproject.toml
```

- `poetry install`

- `poetry run pytest`

### without poetry 

- create virtualenv
- activate virtualenv
- install pytest `pip3 install pytest`
- run python -m pytest

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
-  I have commented my code, particularly in hard-to-understand areas
-  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
-  I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
If your doing testing, I think its best to do it on localhost, if your using your forked repo to deploy somewhere, then go ahead, but dont create a PR unless you got something up and running/it works and follows the Contributing Guidelines, thanks

**Comment by rachmadaniHaryono** [comment]
i just finished creating "simplest" test for every function on most module in the program

after writing this, imo these tests may not be intended to be merged but just request for comment

the tests mostly just run the function from the module with as many unittest.mock.Magicmock parameter as necessary

i also exclude these modules:

- gui: it is generated module (and maybe not needed for the program in current state)
- shared_imports: only import


from that i found many error, but these are domminant error

- TypeError, this could mean it can't be used with Magicmock and require better test input
- OSError, it could mean the function require input. this could be valid but there are some instance that it is better to split between user interface and business logic
- FileNotFoundError, the function require some file to be exist
- UnboundLocalError, the error happen when error not handled correctly and variable don't exist in certain condition see also comment below

---

from that i can recommend some tips/info

- need timeout, because this could hang forever

https://github.com/ThioJoe/YT-Spammer-Purge/blob/70bedd9a085982f38d60eb6c8a9f9b65ed014a2f/Scripts/community_downloader.py#L40

https://github.com/ThioJoe/YT-Spammer-Purge/blob/887460452f6834d973480e502388fb0413319c4b/Scripts/files.py#L324


- better use string for this if not could raise TypeError : `print(str(e)+ "\n")`

https://github.com/ThioJoe/YT-Spammer-Purge/blob/887460452f6834d973480e502388fb0413319c4b/Scripts/files.py#L175

- handle UnboundLocalError

https://github.com/ThioJoe/YT-Spammer-Purge/blob/887460452f6834d973480e502388fb0413319c4b/Scripts/files.py#L653

https://github.com/ThioJoe/YT-Spammer-Purge/blob/887460452f6834d973480e502388fb0413319c4b/Scripts/files.py#L780

- running `files.check_lists_update` could be rate limited by github

---

not from the error but related to this pr

- no test 

from checklist

> I have made corresponding changes to the documentation

> I have added tests that prove my fix is effective or that my feature works

but there is no test or guide on how to test it from CONTRIBUTING.md

i assume it mean developer have to run it and check for any error

- non non-standard library for testing

from CONTRIBUTING.md

> Avoid adding new non-standard libraries if at all possible.
> If you have an idea that would require one,
> please suggest it as an issue first instead of going through all the work and submitting a pull request.

but i recommend pytest over unittest for simplicity and avoid boilerplate

- keep it simple

from CONTRIBUTING.md

> If you'd like to make a pull request to contribute,
> please keep it simple.
> If you use some higher level techniques I don't understand,
> I'm not going to approve it because I won't be able to maintain it.

because of this i think i want this pr to be commented rather than merged

even if i write `"simplest" test` above , it may not be for others

as note, pytest command run perfectly locally on https://github.com/ThioJoe/YT-Spammer-Purge/commit/887460452f6834d973480e502388fb0413319c4b

- others

CONTRIBUTING.md

> Please don't make a pull request with a bunch of changes in syntax just for the sake of 'best practices' 
> (ex: changing "if blah == False" to "if not blah").
> Unless something makes a difference to performance frankly I don't care.

while i understand the reason, it could be harder for other developer to check/test the function

**Comment by EthanHindmarsh** [comment]
> but i recommend pytest over unittest for simplicity and avoid boilerplate

I think a requirements-dev.txt would work fine to resolve the issue -- Not everyone needs to install pytest, only developers
Pytest is fairly standard in the context of the python community, I don't think it would be an issue as long as only developers would need to install it

> but there is no test or guide on how to test it from CONTRIBUTING.md

Yes, the checklist was taken from a larger repo, so not all of it is 100% applicable
I would support tests being added though👍

Honestly, I'm not sure what half of what `test_main.py` is doing, 
Not to be rude in any way, but if I can't read it, I'm not sure Thio could maintain it, and I'm pretty sure that's the standard for a PR being accepted

Also, what's the point of this?
```py
def test_ajax_request():
    if True:
        pytest.skip("run forever")
    cd.ajax_request(MagicMock(), MagicMock(), MagicMock())
```

**Comment by rachmadaniHaryono** [comment]
> I think a requirements-dev.txt would work fine to resolve the issue

i do hope #459 can be merged.

in that pr i already add pytest so other can move from requirements.txt to poetry

>  I would support tests being added though+1

#:+1: 

> Also, what's the point of this?
> 
> ```python
> def test_ajax_request():
>     if True:
>         pytest.skip("run forever")
>     cd.ajax_request(MagicMock(), MagicMock(), MagicMock())
> ```

that is  where i found that ajax_request can hang forever when no timeout


> Honestly, I'm not sure what half of what `test_main.py` is doing, 

the answer is this `the tests mostly just run the function from the module with as many unittest.mock.Magicmock parameter as necessary`


> Not to be rude in any way, but if I can't read it, 
> I'm not sure Thio could maintain it, 
> and I'm pretty sure that's the standard for a PR being accepted

it is okay and i expected as i write above

> even if i write "simplest" test above , it may not be for others

i think there should be better way to start unittesting the program rather than this pr

also i found out that this program could have side effect if run from another python script

also thank you for comment, that is the response that i expected

**Comment by rachmadaniHaryono** [comment]
i will close this pr and create pr with smaller change for easier review

see #536 for starter

**Pull request closed without merging**
