### PR TITLE
Resolve #533

### LINKED ISSUE #533: [Bug]: Sensitive-Smart Mode identifies itself as Auto-Smart Mode
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Selecting Sensitive-Smart mode for the first time was very confusing as it prints out all the same output as Auto-Smart mode except for the very last line warning about false positives. I think this should be changed, at least to display the correct mode at the top of the output.

### Release version

git-224bb22

### Steps to reproduce

1. Choose scan option 1, 2, or 3.
2. Enter needed data and confirm.
3. Choose identify method number 2.
4. Observe confusing output (below).

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
-------------------------------------------------------
~~~~~~~~~~~ Choose how to identify spammers ~~~~~~~~~~~
-------------------------------------------------------
 1. (RECOMMENDED): Auto-Smart Mode: Automatically detects multiple spammer techniques
 2. Sensitive-Smart Mode: Much more likely to catch all spammers, but with significantly more false positives
 3. Enter Spammer's channel ID(s) or link(s)
 4. Scan usernames for criteria you choose
 5. Scan comment text for criteria you choose
 6. Scan both usernames and comment text for criteria you choose
 7. ASCII Mode: Scan usernames for ANY non-ASCII special characters (May cause collateral damage!)
 Note: With 'Not Your Channel Mode' enabled, you can only report matched comments while using 'Auto-Smart Mode'.

Choice (1-7): 2

----------------------------------------------- Auto-Smart Mode -----------------------------------------------
~~~ This mode is a spammer's worst nightmare. It automatically scans for multiple spammer techniques ~~~

 > Extremely low (near 0%) false positives
 > Detects whatsapp scammers and '18+ spam' bots
 > Easily cuts through look-alike characters and obfuscations, including impersonating usernames
 > NOTE: In sensitive mode, expect more false positives. Recommended to run this AFTER regular Auto Smart Mode.

Press Enter to Begin Scanning...
```

### Screenshots

Untitled

### PR DESCRIPTION
**Pull request by EthanHindmarsh**
Check whether or not sensitive, and print the name accordingly
An F-String could be used, but I thought this would be more readable 👍

Also, I think there are way too many print statements used in this repo 😂
I might go through and clean it up, would definitely improve performance.

Resolves #533

### CODE REVIEW

**Comment by EthanHindmarsh** [comment]
Hold: Commits from my other branch were pulled in -- Forgot to rebase

**Comment by EthanHindmarsh** [comment]
Sorry about the excess changes -- My formatter automatically runs before I save a python file 😅
Reopen: Removed changes from other branch ( #510 )

**Comment by rachmadaniHaryono** [comment]
basically the change is this

https://github.com/ThioJoe/YT-Spammer-Purge/pull/535/files#diff-462f2a2e0a188cdecbfe3b181d1ccd12912e2d48fc0b4613ed27a4d977f79763R281-R284

but i think your formatter trim trailing whitespace

maybe ignore it with git?

https://stackoverflow.com/questions/41879816/how-to-ignore-trailing-whitespace-errors-with-git-stash

**Comment by EthanHindmarsh** [comment]
> basically this is the only change
>
> https://github.com/ThioJoe/YT-Spammer-Purge/pull/535/files#diff-462f2a2e0a188cdecbfe3b181d1ccd12912e2d48fc0b4613ed27a4d977f79763R281-R284

Yes

> but i think your formatter trim trailing whitespace
>
> maybe ignore it with git?
> 
> https://stackoverflow.com/questions/41879816/how-to-ignore-trailing-whitespace-errors-with-git-stash

Thanks, I'll check it out 👍
I just added the plugin to my neovim earlier today, didn't realize it did that 😅

**Comment by EthanHindmarsh** [comment]
> basically this is the only change
>
> https://github.com/ThioJoe/YT-Spammer-Purge/pull/535/files#diff-462f2a2e0a188cdecbfe3b181d1ccd12912e2d48fc0b4613ed27a4d977f79763R281-R284

@rachmadaniHaryono #533 labeled it as a bug, so this is a solution to the 'bug'

**Comment by KendallDoesCoding** [comment]
If this PR fixes #533 please make the description the following the link the issue:

Fixes #533

I think even Fix #533 will work.

**Comment by EthanHindmarsh** [comment]
> If this PR fixes #533 please make the description the following the link the issue:
> 
> Fixes #533
> 
> I think even Fix #533 will work.

Did you look at the title..?

**Comment by EthanHindmarsh** [comment]
Fetch upstream to ensure no merge conflicts ^^

**Comment by KendallDoesCoding** [comment]
> > If this PR fixes #533 please make the description the following the link the issue:
> > Fixes #533
> > I think even Fix #533 will work.
> 
> Did you look at the title..?

Yes but the text needs to be in the description or the issue doesnt get linked LOL

**Comment by rachmadaniHaryono** [comment]
just to clarify 

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> You can link an issue to a pull request manually or using a supported keyword in the pull request description.

**Comment by KendallDoesCoding** [comment]
> just to clarify
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
> 
> > You can link an issue to a pull request manually or using a supported keyword in the pull request description.

Ok, but it didnt link when it was in the title?

**Pull request merged**
