### PR TITLE
Major fix on line 275.

### PR DESCRIPTION
**Pull request by joevans**
This fix is one that you have see to believe. Internet saved. :)

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
Update title to, fix typo in script lol

**Comment by nick-potts** [comment]
Shocking... but I fixed this on my pull request with repost detection

**Comment by KendallDoesCoding** [comment]
> Shocking... but I fixed this on my pull request with repost detection

Please mention the PR

**Comment by nick-potts** [comment]
#424 @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> #424 @KendallDoesCoding 

Saw that now, sorry got confused because I didnt see any PR's under @joevans's name, and I didnt see the name of you, the person who commented. But, I still prefer this PR will remain open, incase @ThioJoe doesnt want to merge #424 .

**Comment by joevans** [comment]
Closing as I am late to saving the internet. Thank you for updating me, folks!

**Comment by KendallDoesCoding** [comment]
> Closing as I am late to saving the internet. Thank you for updating me, folks!

No, as I said, your not late, please keep this open incase @ThioJoe decides against not merging #424

**Comment by KendallDoesCoding** [comment]
> > Closing as I am late to saving the internet. Thank you for updating me, folks!
> 
> No, as I said, your not late, please keep this open incase @ThioJoe decides against not merging #424

This seems to have been commited, so dw about reopening this now. Thanks

**Pull request closed without merging**
