### PR TITLE
Use modern project structure

### PR DESCRIPTION
**Pull request by dekoza**
This project is awesome but could use some modern programming techniques :wink: 

Right now I just updated the project's structure to enable upcoming features that include:

- using async for faster operations
- proper CLI with params, usable in automation
- usable as python library
- proper instalation - just using pip/poetry/whatever, no special scripts
- easier configuration with files saved in proper places
- use pre-commit, black, pyupgrade, etc.
- other QoL changes

### CODE REVIEW

**Comment by rcmaehl** [comment]
Wouldn't this be best to be split into multiple PRs for each major change instead of a PR for an entire rewrite?

**Comment by UP929312** [comment]
This is quite a lengthy commit, which would make it hard to confirm everything is working fine, perhaps split it into more selected meaningful commits?

**Comment by EthanHindmarsh** [comment]
76 files changed 😮
You might want to fix your GPG signing -- all of your commits are unverified

**Comment by dekoza** [comment]
Well, this is rather a documentation of my work if anything else. If original project had some tests it would be easier to prove that this works :wink:

> Wouldn't this be best to be split into multiple PRs for each major change instead of a PR for an entire rewrite?

Yes but no :wink: The original is so far away in terms architecture that any meaningful modernization yields a huge diff. Use `black`? Huge diff. Use `pyupgrade`? Huge diff. Use reasonable project structure? Huge diff. There's basically no good way around it. I figured that I'd simply make a total makeover and leave it for @ThioJoe to test it and (hopefully) approve it. I think it's the best (and fastest) way at the moment.

**Comment by EthanHindmarsh** [comment]
> The original is so far away in terms of architecture that any meaningful modernization yields a huge diff. Use `black`? Huge diff. Use `pyupgrade`? Huge diff. Use reasonable project structure? Huge diff. 

I've cut the majority of the Black PR out, down to 68 added lines, but once implemented it'll definitely mess up every open PR
It's best to bite the bullet while we still can else be doomed to become a lower quality project 👍
This PR looks like it could be split into documentation changes, configuration changes (workflows, Makefile, etc), and code changes -- Would definitely cut down on the amount of work needed to accept one PR

**Comment by dekoza** [comment]
I can turn this into only-file-structure changes and necessary imports refactor - without black and pyupgrade adding their changes. It's the minimum at the moment. Then black and pyupgrade and then more changes.

As I said earlier - this code basically needs to be rewritten from scratch to be truly maintainable.

**Comment by ThioJoe** [comment]
I don't know understand the purpose of 99% of this

**Comment by dekoza** [comment]
Long story short, the main purpose is for the project to be more maintainable so that other people can easily improve on it.

**Comment by dekoza** [comment]
I'm putting the "WIP" label back - during testing I found I need to work a bit more on file loading (`files.py`) - that one's very messed up.

**Comment by bsnk-dev** [comment]
> I don't know understand the purpose of 99% of this

If we had a proper rewrite we could use CLI ui maps and GUI maps so we could say have a web interface for it or the classic interface. It would be really slick in the end.

**Comment by dekoza** [comment]
@bsnk-dev that's exactly my point, thanks :slightly_smiling_face:

**Comment by dekoza** [comment]
OK, fixed `files.py` among others. On to resolving merge conflicts :wink:

**Comment by UP929312** [comment]
> Long story short, the main purpose is for the project to be more maintainable so that other people can easily improve it.

As far as I'm aware, ThioJoe has expressed this isn't important to him, hence denying my pull request:
https://github.com/ThioJoe/YT-Spammer-Purge/pull/430

Read more about it there,
I showed best practices and improved performance, but was denied because "What's the point"

Yeah....

**Comment by dekoza** [comment]
> I showed best practices and improved performance, but was denied because "What's the point"

@UP929312  In that case I invite you to work with me on the rewrite on my fork :smile: Just please give me a couple days to redesign it and then we can start the rewrite :tada:

**Comment by rachmadaniHaryono** [comment]
1. 

> ++ b/.github/ISSUE_TEMPLATE/bug_report.md

optional or unnecessary, i think current bug report is good enough

2. 

> +++ b/.github/ISSUE_TEMPLATE/config.yml
> +++ b/.github/ISSUE_TEMPLATE/spam_detection.yaml

unnecessary, i think it is because the repo renamed

3.

> +++ b/.github/workflows/ci.yml

optional, require pyproject, duty

4. 

> --- a/.github/workflows/docker-build.yml
> --- a/docker-compose.override.yml

unnecessary(?), why it is deleted?

5. 

> +++ b/.gitignore

optional, maybe add entries instead replace current one, also group new entries

6. 

> +++ b/.pre-commit-config.yaml

optional but necessary, if possible create new pr only this because this is important

but it is necessary to document how to use pre commit

7.

> +++ b/CHANGELOG.md

optional maybe unnecessary, unnecessary because it depend on author/maintainer to maintain changelog see also comment below


maybe use commitizen changelog to automate this?

https://github.com/commitizen-tools/commitizen

https://commitizen-tools.github.io/commitizen/changelog/

8. 

> +++ b/CODE_OF_CONDUCT.md

unnecessary, based on https://github.com/ThioJoe/YT-Spammer-Purge/pull/103

9.

> +++ b/CONTRIBUTING.md

optional, require makefile, cli feature, duty

maybe mention commit message structure as recommendation

if not maybe the repo can use commitizen pre commit hook to help developer

https://github.com/commitizen-tools/commitizen

> ## Pull requests guidelines

is this neccessary?

10. 

> +++ b/Makefile

optional, require pyproject, duty


11. 

> +++ b/OLD_README.md

unnecessary, this will make confusion

if the goal is to change the readme just delete the required section

git will remember deleted text


12. 

> +++ b/README.md

optional,

maybe dont' remove text old readme and put new entries

> yt-spam-purge requires Python 3.10 or above.

i test it and it actually only require python3.6+

does pyenv installation required here or just put the link to pyenv docs?

mention installing from github repo?

```shell
> pip3 install https://github.com/ThioJoe/YT-Spammer-Purge/archive/refs/heads/main.zip
> # or 
> pipx install https://github.com/ThioJoe/YT-Spammer-Purge/archive/refs/heads/main.zip
```

also it require that this program to be uploaded to pypi


13. 

> +++ b/src/yt_spam_purge/__init__.py
> +++ b/src/yt_spam_purge/__main__.py
> +++ b/src/yt_spam_purge/auth.py
> +++ b/src/yt_spam_purge/cli.py
> +++ b/src/yt_spam_purge/community_downloader.py
> +++ b/src/yt_spam_purge/gui.py
> +++ b/src/yt_spam_purge/operations.py
> +++ b/src/yt_spam_purge/prepare_modes.py
> +++ b/src/yt_spam_purge/utils.py
> --- a/Scripts/prepare_modes.py
> --- a/YTSpammerPurge.py
> rename to src/yt_spam_purge/assets/cancelButton.png
> rename to src/yt_spam_purge/assets/default_config.ini
> rename to src/yt_spam_purge/assets/executeButton.png
> rename to src/yt_spam_purge/assets/icon.png
> rename to src/yt_spam_purge/assets/inputSubmitButton.png
> rename to src/yt_spam_purge/assets/inputTextBox.png
> rename to src/yt_spam_purge/assets/outputTextBox.png
> rename to src/yt_spam_purge/assets/rootZoneDomainList.txt
> rename to src/yt_spam_purge/assets/SpamAccountsList.txt
> rename to src/yt_spam_purge/assets/SpamDomainsList.txt
> rename to src/yt_spam_purge/assets/SpamThreadsList.txt
> rename to src/yt_spam_purge/assets/SpamVersionInfo.json
> rename to src/yt_spam_purge/auth.py
> rename to src/yt_spam_purge/files.py
> rename to src/yt_spam_purge/shared_imports.py
> rename to src/yt_spam_purge/utils.py
> rename to src/yt_spam_purge/validation.py

?, i will comment it later

14. 

> +++ b/config/coverage.ini

optional, require coverage

15. 

> +++ b/config/flake8.ini

optional

16.

> +++ b/config/mypy.ini
> +++ b/config/pytest.ini

optional, require mypy and pytest

maybe merge it to pyproject.toml

17. 

> +++ b/docker/Dockerfile
> +++ b/docker/docker-compose.yml

optional, is it necessary to move them

18.


> +++ b/docs/changelog.md
> +++ b/docs/code_of_conduct.md
> +++ b/docs/contributing.md
> +++ b/docs/credits.md
> +++ b/docs/css/mkdocstrings.css
> +++ b/docs/index.md
> +++ b/docs/license.md
> +++ b/docs/macros.py
> +++ b/docs/reference/cli.md
> +++ b/mkdocs.yml

optional, but it is really needed to get overview of the module

19.

> +++ b/duties.py

optional, require pre commit, pyproject

20. 

> --- a/install.sh
> --- a/install_full.sh
> --- a/requirements.txt

optional, only after pyproject and packaging work


21. 

> +++ b/pyproject.toml

optional, 


related https://github.com/ThioJoe/YT-Spammer-Purge/pull/459

22. 

> +++ b/scripts/multirun.sh

optional, require pyproject

maybe rather than script such as multirun.sh use tox

https://tox.wiki/en/latest/example/package.html#poetry

23. 

> +++ b/scripts/setup.sh

optional


24. 


> +++ b/tests/__init__.py

optional, maybe unnecessary

based on this

https://scikit-hep.org/developer/pytest

> In general,
> do not place a __init__.py file in your tests;
> there’s not often a reason to make the test directory importable,
> and it can confuse package discovery algorithms.

it maybe more complicated than that

https://docs.pytest.org/en/latest/goodpractices.html

25. 

> +++ b/tests/test_cli.py

optional, require cli

--- 

> rachmadaniHaryono I did what I could to minimize the changes.
> I used [copier-poetry](https://github.com/pawamoy/copier-poetry) to create the basic directory structure and then moved most of the files into proper places.
> Then I refactored imports so that everything should work.
> Right now - since there are no tests - I'm trying to check if everything still works fine.
> If you ignore those several files added by `copier-poetry`,
> you'll see that the changes of imports are in fact small.

i agree with rcmaehl and UP929312 that this pr is too big

but the positive thing is that some of the change can be split into multiple pr


> > I showed best practices and improved performance, but was denied because "What's the point"
> 
> UP929312 In that case I invite you to work with me on the rewrite on [my fork](https://github.com/dekoza/yt-spam-purge) smile 
> Just please give me a couple days to redesign it and then we can start the rewrite tada

at this point, i don't recommend it 

https://www.bacula.org/all-project-forks-are-not-bad/

> In general, I believe that project forks are not good.
> I wouldn’t really say that forks are bad,
> but they do tend to duplicate effort and split the community.
> They certainly are justified if the particular project is stalled or is not willing to meet the needs of a community or if the new project has a different goal.

i still think this project is still salvageable


---

about the project structure

https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

i understand the benefit of using src structure

but before moving the file, it require the program to handle custom folder input / path / config

there are already bugs about client_secret.json location


https://github.com/ThioJoe/YT-Spammer-Purge/issues/479
https://github.com/ThioJoe/YT-Spammer-Purge/issues/266

maybe create unittest first to make sure current program is working

**Comment by dekoza** [comment]
Thank you for the extensive feedback, @rachmadaniHaryono !

Most of the optional files were created by `copier-poetry` and can obviously be removed or adjusted.

Right now code from this PR is installable using pip and the main script is run using `ytsp` (shorthand for "youtube spam purge") command. 

I personally don't think this project at this state is salvagable, especially given ThioJoe's attitude.

I'm closing this PR - you all are right that it's too big and drastic. In my opinion you need to cut the cancer as fast as possible instead of just poking around :wink:  But in any case I'll just go on with my fork/rewrite instead of arguing why each change is important. I'd rather spend that time programming :slightly_smiling_face: Hopefully I can deliver rather quickly and then we can restart this conversation :wink:

**Comment by EthanHindmarsh** [comment]
> I personally don't think this project at this state is salvagable, especially given ThioJoe's attitude.

@dekoza Yeah, I hope the project could move to better hands, not sure if Thio would be willing to give it up though

**Comment by dekoza** [comment]
@EthanHindmarsh I honestly hope he doesn't give it up - he should be this project's Benevolent Dictator for Life :smiley: Maybe with time some developer(s) will earn his trust and he'll allow them to make an official rewrite. Until then we should be thankful he published his code on GPL.

**Comment by compsup** [comment]
Like any project, when it get's big enough it will need to be refactored, however I agree that this project in its current state does not need a refactor but instead a ground up rewrite with just the main ideas implemented. Too prevented this from happening again the rewrite needs too follow these concepts. (All these are just summarising the conversation above)

- Proper OOP with ALL logic functions being completely testable
- Test driven development
- Proper PyPi program structure so you can easily publish on PyPi
- A agreed upon formatter (seems like black has been agreed upon)
- Write it so we can use CLI ui maps
- Make the api calls thread safe(async)
(I don't take credit for the above list, its a summary of the massive conversation)

The second that we relax these is the second the project collapses and becomes un-maintainable.

**Comment by pawamoy** [comment]
Hey, @dekoza, thanks for promoting my `copier-poetry` template haha :smile: 
I have a new one based on PDM instead, if you'd like to give it a try, at I don't maintain the Poetry version anymore! [copier-pdm](https://github.com/pawamoy/copier-pdm)

**Comment by ThioJoe** [comment]
If I was going to do a ground up re-write I definitely wouldn't use python again lol

**Comment by UP929312** [comment]
> If I was going to do a ground up re-write I definitely wouldn't use python again lol. Good for fast development, but several disadvantages, including it seems to be harder to find bugs until runtime

Runtime bugs would be fixed if you actually listened to people who suggest things like MyPy and improved the code quality, if you leave it in the mess it's in of course bugs are going to exist...

**Comment by compsup** [comment]
> If I was going to do a ground up re-write I definitely wouldn't use python again lol. Good for fast development, but several disadvantages, including it seems to be harder to find bugs until runtime

See that's what tests do. Have properly written code and have full test coverage, then these small bugs will be shown and get fixed before you even run the program. No matter what language you write it in, if you don't keep the code quality high and have tests it won't make a difference.

**Pull request closed without merging**
