### PR TITLE
Website for Your Tool "The Youtube Spammer Purge"

### PR DESCRIPTION
**Pull request by raghunandhanvr**
# ThioJoe

# Website for Your Youtube Spammer Purge:

## The Live Website: [https://raghuvr.tech/ThioJoe/](https://raghuvr.tech/ThioJoe/)

Hey Bro!

Really an Amazing work for Spam Reporting

This website Im sharing now is been built with ReactJS which contains downloadble and Some Details about the tool. 

The Downloadble will be given to direct button option once the website is been done.

I need your permission to build website for your tool will may also give nice ui page for direct download option and with a good UI.

You can check the live website and send me a mail or pull this repo to your main so that everyone can contribute and make this website better.

### CODE REVIEW

**Comment by raghunandhanvr** [comment]
If anyone interested to Contribute this website for a better UI and Stuffs, Reply this message

**Comment by KendallDoesCoding** [comment]
This is great, but I don't think ThioJoe will want to add the website code in this repo.. Feel free to make your own repo and put the code in there and then if ThioJoe wants, as you put in so much effort he can link the website or something in the README.

**Comment by KendallDoesCoding** [comment]
This is a bug, this project only has 37 contributors, not 1.6k lol
image

**Comment by raghunandhanvr** [comment]
> This is a bug, this project only has 37 contributors, not 1.6k lol
> image

 Yeah bro. I just added that pic as it suits that theme. Many things to be modified yet😃. Will do that.

**Comment by raghunandhanvr** [comment]
> This is great, but I don't think ThioJoe will want to add the website code in this repo.. Feel free to make your own repo and put the code in there and then if ThioJoe wants, as you put in so much effort he can link the website or something in the README.

Currently working on creating cards for different OS downloadable files with a cdn which has all downloadable files with a single click. Newer version updates will be uploaded to that cdn and from there users can download this tool. Can you link me with someone for those things?

**Comment by KendallDoesCoding** [comment]
> > This is great, but I don't think ThioJoe will want to add the website code in this repo.. Feel free to make your own repo and put the code in there and then if ThioJoe wants, as you put in so much effort he can link the website or something in the README.
> 
> Currently working on creating cards for different OS downloadable files with a cdn which has all downloadable files with a single click. Newer version updates will be uploaded to that cdn and from there users can download this tool. Can you link me with someone for those things?

I can't really help you with this, sorry.

**Comment by EthanHindmarsh** [comment]
Your website is very nice, but I do not think it should be part of this repo - This repo is for the YT-Spammer-Purge tool, and users pretty much download this repo directly, Users do not need to download a website to run YT-Spammer-Purge
I would leave it at putting a link to the website in the README, and having the website be a separate repo 👍
Whether or not Thio wants a dedicated website for YT-Spammer-Purge is up to him 🤷

**Comment by raghunandhanvr** [comment]
> Your website is very nice, but I do not think it should be part of this repo - This repo is for the YT-Spammer-Purge tool, and users pretty much download this repo directly, Users do not need to download a website to run YT-Spammer-Purge I would leave it at putting a link to the website in the README, and having the website be a separate repo 👍 Whether or not Thio wants a dedicated website for YT-Spammer-Purge is up to him 🤷

Yeah. If Thio needs a website for his tool, Someone let me know so that I can work with some new features and stuffs for this website 😄

**Comment by KendallDoesCoding** [comment]
> Your website is very nice, but I do not think it should be part of this repo - This repo is for the YT-Spammer-Purge tool, and users pretty much download this repo directly, Users do not need to download a website to run YT-Spammer-Purge I would leave it at putting a link to the website in the README, and having the website be a separate repo 👍 Whether or not Thio wants a dedicated website for YT-Spammer-Purge is up to him 🤷

Yeah!

**Comment by ThioJoe** [comment]
Yea to be honest I don't really think a website is necessary and would just be another thing to maintain

**Comment by raghunandhanvr** [comment]
> Yea to be honest I don't really think a website is necessary and would just be another thing to maintain

Yeah I can understand. But we got many contributors to maintain these web stuffs. Adding this website to your README or setting that website for direct download will be much easier for People who would like to use your tool. 

Other contributions for tool will be on one side and Web people will be contributing this stuff.

**Pull request closed without merging**
