### PR TITLE
Update menu logic

### PR DESCRIPTION
**Pull request by Primus27**
# Related Issue/Addition to code

- Reduced the number of variables that need updating when an additional option is added to any of the menus
- Increases code readability and maintainability

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- No additional action is needed. When a user selects a menu number, the corresponding string is retrieved. If the user selects the string, no additional steps are taken since it is already valid and does not require reassignment.

# Additional Info

Menu options not relating to numbers (e.g. 'chosenvideos' [here](https://github.com/ThioJoe/YT-Spammer-Purge/blob/224bb22306fa3d354c94c43b0ea048abf8ce903a/YTSpammerPurge.py#L407) ) don't seem to be required and are not documented anywhere (they just seem like alternative values the user can enter).

While this functionality has been retained, these values have changed slightly (e.g. 'chosen**V**ideos' instead of 'chosenvideos') since it's more effort to include these options if they are not used. Instead, users can either enter numbers (as before) or enter the exact string the mode should have.

Again, this shouldn't be a big deal as it was undocumented and inconvenient compared to selecting the number from the list.

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by ThioJoe** [comment]
Actually the reason for the lowercase menu strings is because that's what comes from the config file

**Comment by ThioJoe** [comment]
I'll add some extra comments but gonna close this because it breaks everything from the config ha

**Comment by Primus27** [comment]
@ThioJoe
Ah, right. Good catch. I'm happy to fix that, making sure the config values work properly but what are your thoughts?

My main concern is that the list of valid choices (e.g. [L404](https://github.com/ThioJoe/YT-Spammer-Purge/blob/224bb22306fa3d354c94c43b0ea048abf8ce903a/YTSpammerPurge.py#L404)) is annoying to maintain since it's not automatically derived from the if/else logic. If it's ever forgotten/missing from the list, that menu option doesn't work so I'm sure you can see the value in removing that potential issue.

**Comment by Primus27** [comment]
I've updated the script to ensure compatibility. As seen [here](https://github.com/Primus27/YT-Spammer-Purge/commit/db541dc5add23b99f611676dd2a0404785749b13).

Could you please repon the issue so that it can be reviewed?

**Comment by Primus27** [comment]
@ThioJoe

**Comment by ThioJoe** [comment]
Hm yea I could see the benefit of the changes. I see you've deleted your fork of the repo so if I end up adding any of it i'll add you as a co-author on the commit

**Pull request closed without merging**
