### PR TITLE
whitelist renamed to allowlist

### PR DESCRIPTION
**Pull request by notoriousjere**
Changes "whitelist" to "allowlist" because it is a more modern term.

## Type of change
- Naming change

# Proposed Changes
- Changes "whitelist" to "allowlist" because it is a more modern and clear term and removes racial bias.

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Future considerations:
- Rename all variations of "Black<something>" in the regex filtering operations to "Deny" or similar. Wanted to keep this PR small.

### CODE REVIEW

**Comment by Firecul** [comment]
There is more than one code reference to `whitelist` still there?

**Comment by notoriousjere** [comment]
> There is more than one code reference to `whitelist` still there?

Yes but only as needed to change the name of a preexisting whitelist.txt file to avoid manually having to change the filename. More importantly is that the user facing prints were changed.

**Comment by ThioJoe** [comment]
meh

**Comment by notoriousjere** [comment]
lol i tried. have fun with your repo.

**Pull request closed without merging**
