### PR TITLE
Add submodule folder

### PR DESCRIPTION
**Pull request by Firecul**
# Addition to code

Converting included spam lists to a submodule. It's not strictly necessary but saves keeping the files up to date manually.

I haven't made the corresponding changes to the python code to accommodate for this change so until that is done, it should be considered **a breaking change**.

## Type of change

Please delete options that are not relevant.

- [X] Breaking change --- For now.
- [ ] New feature (non-breaking change which adds functionality) --- eventually

## Checklist:

- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by Firecul** [comment]
From talking to you in https://github.com/ThioJoe/YT-Spammer-Purge/discussions/666#discussioncomment-2197727 @ThioJoe you can see the actual submodule part is easy. I don't have enough knowledge of python to adjust the code to accommodate the lists being an extra folder deep compared to the rest of the files in the `asset` folder so I'll leave that part for you or others. I am open to any input on that one.

**Comment by rachmadaniHaryono** [comment]
maybe just put everything on assets to other repo. it would make no change on current structure

**Comment by Firecul** [comment]
> maybe just put everything on assets to other repo? it would make no change on current structure

That would be fine but the `icon.png` is used in the readme and if something were to go wrong it would mean the GUI portion of the program would have no buttons etc.

**Comment by rachmadaniHaryono** [comment]
i can see that happen because 

1. this repo have to accept this pr
2. submodule repo have to accept pr for other files

so between 1 and 2 readme will not rendered correctly

**Comment by Firecul** [comment]
Hence why I was just keeping it to the spam lists

**Comment by rachmadaniHaryono** [comment]
i still recommend to do it rather than just spam lists because you still have to make change to program if it just spam lists

so basically

1. set gitmodule
```ini
[submodule "assets/YT-Spam-Lists"]
	path = assets
	url = https://github.com/ThioJoe/YT-Spam-Lists.git
```
2. create pr on another repo for other file on assets
3. this pr and pr from step 2 have to be accepted simultaneously

if it run correctly, the only change is on gitmodule

but other repo will have more files after this

i will try on my fork if above step is working correctly

**Comment by Firecul** [comment]
> i still recommend to do it rather than just spam lists because you still have to make change to program if it just spam lists

The reason I don't want to do it that way is that this repo is for the program itself, https://github.com/ThioJoe/YT-Spam-Lists is for the lists. If we were going to move program components there then why not just manage the lists in this repo instead?
Program files should all remain in the program's own repo IMO, there is no point in spreading it around github.

Pulling the lists is already being done, this makes it easier to manage. If you were to change the GUI for the program you'd have to edit 2 repos, which to me isn't the best way to do it.

**Comment by rachmadaniHaryono** [comment]
[> If we were going to move program components there then why not just manage the lists in this repo instead?

](https://github.com/rachmadaniHaryono/YT-Spammer-Purge/tree/feature/submodule

https://github.com/rachmadaniHaryono/YT-Spam-Lists

this is my attempt to do it on my fork

no structure change, but non-spam-list files will not be used correctly on readme (i still haven't tried on the program itself)

> If we were going to move program components there then why not just manage the lists in this repo instead?

i thought that is why there is point on contributing.md to create issue YT-Spam-Lists to modify spam-list files

> Pulling the lists is already being done, this makes it easier to manage.
> If you were to change the GUI for the program you'd have to edit 2 repos, which to me isn't the best way to do it.

my assumption

if you edit any file under assets, your change will be reflected to YT-Spam-Lists repo

the opposite will also happen

---

> Program files should all remain in the program's own repo IMO, there is no point in spreading it around github.

i do think `Program files should all remain in the program's own repo` this part is correct

so possible solution so far

1. keep structure , move all files to YT-Spam-Lists and link YT-Spam-Lists to assets folder
2. dont keep structure, link YT-Spam-Lists to assets/YT-Spam-Lists and change the program
3. create new folder (e.g. `program_assets`), move non-spam-list files to new folder, link YT-Spam-Lists to assets and change the program
)

**Comment by Firecul** [comment]
> my assumption
> 
> if you edit any file under assets, your change will be reflected to YT-Spam-Lists repo
> 
> the opposite will also happen

That is not the case, it's importing only.

**Comment by rachmadaniHaryono** [comment]
so if i edit yt-spam-list it will not reflected to this repo?

**Comment by Firecul** [comment]
If you edit yt-spam-list it will affect this repo but trying to edit the files here won't change yt-spam-list in the slightest

**Comment by ThioJoe** [comment]
Ok cool i'll have a look at how this works

**Comment by Firecul** [comment]
Rebase then list update ☝️

**Comment by KendallDoesCoding** [comment]
Hey @Firecul , any update on this?

**Comment by Firecul** [comment]
Not really, I haven't had time to look into this part yet
> I don't have enough knowledge of python to adjust the code to accommodate the lists being an extra folder deep compared to the rest of the files in the `asset` folder so I'll leave that part for you or others. I am open to any input on that one.

**Comment by Firecul** [comment]
I'm just going to close this for now, I'm not able to put in the time to get this method working fully.

**Pull request closed without merging**
