### PR TITLE
Add new package to fedora

### PR DESCRIPTION
**Pull request by YuvanMichael**
Should help avoid installing issues which might happen after cloning the repository.

# Added new package for fedora

- Fixes #
- Added python3-devel

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Proposed Changes
- Add a new package to fedora

# Additional Info
- issue #739 

## Checklist:

- [x] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [x] I have tested this myself
- [x] There is no too much technical stuff
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by YuvanMichael** [comment]
I have tested this myself and carefully checked terminal outputs. Shouldn't cause any damage to user experience. Script should function normally.

**Comment by YuvanMichael** [comment]
I request maintainers/contributors or anyone who knows what they are doing. To add the same package (names might differ) for other distributions like debian and arch.

**Comment by YuvanMichael** [comment]
cause of this pull request. #739

**Comment by YuvanMichael** [comment]
I have only modified install.sh

**Comment by YuvanMichael** [comment]
Also I was checking out the centos code and I think this command (sudo yum remove -y epel-release) is uninstalling epel

**Review by micziz — APPROVED** [review]
LGTM

**Comment by YuvanMichael** [comment]
> LGTM
What does that mean?

**Comment by YuvanMichael** [comment]
If it means look good to me then ok! :)

**Comment by YuvanMichael** [comment]
If its okay with thio joe or any other contributor, I could search online and put the packages for debian and arch.

**Comment by YuvanMichael** [comment]
I'll add packages for debian and arch and other distros. Please give your confirmation again after I make these changes.

**Comment by micziz** [comment]
It means legitimate or looks good to me!

**Review by EthanHindmarsh — APPROVED** [review]
LGTM✅
Seems python3-dev is a commonly required dependency for Levenshtein, might just be best to add it to every install 😅
That's outside the scope of this PR though, and I'm not sure how to check what systems would and wouldn't need it without testing myself

**Comment by EthanHindmarsh** [comment]
> This is a reply to `# Honestly not sure why it's installing epel and then uninstalling`. But, I'm not fully sure. yum is actually the older package manager for fedora. dnf is the new one. Not fully familiar with yum's syntax.

I put that comment there because I didn't write the install commands themselves, I just copied them from the old script into the os-specific install functions, eg. if old script ran `pacman -S python3 python3-pip` for arch, I'd just toss that into install_arch

**Comment by YuvanMichael** [comment]
> > This is a reply to `# Honestly not sure why it's installing epel and then uninstalling`. But, I'm not fully sure. yum is actually the older package manager for fedora. dnf is the new one. Not fully familiar with yum's syntax.
> 
> I put that comment there because I didn't write the install commands themselves, I just copied them from the old script into the os-specific install functions, eg. if old script ran `pacman -S python3 python3-pip` for arch, I'd just toss that into install_arch

We could just remove that uninstall command.

**Pull request merged**
