### PR TITLE
add size badge

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- Add size badge

## Type of change
- [ ] This change requires a documentation update

# Proposed Changes
- Add size badge.

### CODE REVIEW

**Comment by TechStudent11** [comment]
why exactly is this needed (that could be a template question)?

**Comment by Firecul** [comment]
> (that could be a template question)

Now **that** is a good idea.

**Review by EthanHindmarsh — APPROVED** [review]
Neat, not sure how useful it is though?

**Comment by EthanHindmarsh** [comment]
Might be better to have a `docker size` badge :thinking: 
No errors in the HTML though 😆✅

**Comment by KendallDoesCoding** [comment]
> why exactly is this needed (that could be a template question)?

I mean, if someone wants to download this on their PC, and they got very low storage, and want to download the full repo files, to experiment, play around with code, this will be kinda a warning, I believe some very bad pc's have like 1GB a drive or something like that, so if this is a quarter or half a GB it can give them a warning not to download the full repo?

**Comment by KendallDoesCoding** [comment]
> Might be better to have a `docker size` badge 🤔 No errors in the HTML though 😆✅

Yeah good idea, I need to find a badge for that though, I use this size badge in my personal repo so I got that one.

**Comment by KendallDoesCoding** [comment]
> > why exactly is this needed (that could be a template question)?
> 
> I mean, if someone wants to download this on their PC, and they got very low storage, and want to download the full repo files, to experiment, play around with code, this will be kinda a warning, I believe some very bad pc's have like 1GB a drive or something like that, so if this is a quarter or half a GB it can give them a warning not to download the full repo?

but where are the template questions? sorry if this is a stupid question.

**Comment by ThioJoe** [comment]
I don't really see it as necessary, but it would also cause confusion because the .exe is much larger than the size stated, and could cause confusion

**Comment by KendallDoesCoding** [comment]
> I don't really see it as necessary, but it would also cause confusion because the .exe is much larger than the size stated, and could cause confusion

Oh ok, didn't know the .exe file size was bigger.

**Pull request closed without merging**
